Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-12, with the labels that each got.

#583 Add AVX512 code for Smooth Predictors
  Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
  Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
  Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/EbHighbdIntraPredictionTests.cc
  test/EbHighbdIntraPredictionTests.h
Labels: P1, S+, simd

#838 Set RANSAC_NUM_MOTIONS to 1 to speedup global motion estimation
  Source/Lib/Common/Codec/global_motion.h
Labels: S+

#843 Fix build error when UPDATE_CDEF is 0
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
Labels: bugfix

#845 Single av1_make_masked_inter_predictor function for 8 and 10 bit streams
  Source/Lib/Common/Codec/EbInterPrediction.c
Labels: Cleanup

#851 Fix typo from 793785c commit
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
Labels: P1, blocker, bugfix

#837 Single av1_build_obmc_inter_prediction function for 8 and 10 bit frames
  Source/Lib/Common/Codec/EbInterPrediction.c
Labels: Cleanup

#786 Implementation missing C kernels and fix UT AVCStyleMcpTest
  Source/Lib/Common/ASM_SSE2/EbAvcStyleMcp_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/Codec/EbAvcStyleMcp.c
  Source/Lib/Common/Codec/EbAvcStyleMcp.h
  Source/Lib/Common/Codec/EbComputeMean.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/AVCStyleMcpTest.cc
  test/compute_mean_test.cc
  test/ref/EbComputeMean_C.c
Labels: P1, simd

#780 Change -tbr input values from bps to kbps
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: API Change, P2

#801 Fix issues in HbdVariance unittest
  Source/Lib/Common/ASM_SSE2/highbd_variance_impl_sse2.asm
  Source/Lib/Common/ASM_SSE2/highbd_variance_sse2.c
Labels: P1, test

#822 Add tests for palette mode
  test/PaletteModeUtilTest.cc
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
  test/e2e_test/SvtAv1E2ETest.cc
Labels: P2, test

#840 Fix mismatch between C and AVX2 kernel get_eight_horizontal_search_po…
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
Labels: P1, bugfix, test

#793 Fix errors in UT for NoiseExtractTest
  Source/Lib/Common/ASM_AVX2/EbNoiseExtractAVX2.c
  Source/Lib/Common/ASM_AVX2/EbNoiseExtractAVX2.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  test/NoiseExtractTest.cc
Labels: P1, test

#844 Speed up of full_distortion_kernel16_bits_avx2
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Inline_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  test/SpatialFullDistortionTest.cc
Labels: P1, S+, simd

#848 Add unit tests for global motion utility
  test/GlobalMotionUtilTest.cc
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
Labels: test

#823 Fixes for avx512 UT
  test/EbHighbdIntraPredictionTests.cc
  test/InversetransformTests.cc
  test/MotionEstimationTest.cc
Labels: P1, simd, test

#842 Code cleanup for cdef filtering
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCdef.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.h
Labels: Cleanup, P2

#862 Protect the AVX512 code in encodetxb_avx512.c
  Source/Lib/Common/ASM_AVX512/encodetxb_avx512.c
Labels: build, simd

#861 Remove RC 1 and shift RC 3 to RC 2 and RC 2 to RC 1
  Docs/svt-av1_encoder_user_guide.md
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateControlProcess.h
  Source/Lib/Common/Codec/RateControlGopInfo.c
  Source/Lib/Common/Codec/RateControlGopInfo.h
  Source/Lib/Common/Codec/RateControlModel.c
  Source/Lib/Common/Codec/RateControlModel.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
Labels: API Change, Cleanup, Rate Control

#834 Global Motion Estimation Opt
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
Labels: P1, S+

#864 Cleanup Phase I
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingLoop.h
  Source/Lib/Common/Codec/EbCodingUnit.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/EbSegmentation.h
Labels: Cleanup

#773 AUTO_MAX_PARTITION
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_SSSE3/ml_ssse3.c
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Common/Codec/ml.c
  Source/Lib/Common/Codec/ml.h
  Source/Lib/Common/Codec/partition_model_weights.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  test/EbNNPredictTests.cc
  test/GlobalMotionUtilTest.cc
Labels: P1, S+, new feature

#858 Multi-Pass Partitioning Decision (Multi-Pass PD)
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
Labels: P1, S+, blocker

#865 umv0 resource coordinate refine
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: bugfix

#847 Decoder Performance optimization and Intrinsic fixes
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/obmc_sad_avx2.c
  Source/Lib/Common/ASM_SSE2/EbDeblockingFilter_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/intrapred_sse2.asm
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Common/ASM_SSE4_1/EbBlend_sse4.h
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecLF.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecRestoration.c
  Source/Lib/Decoder/Codec/EbObuParse.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: S+, decoder

#785 Add optimization level "-asm" to limit cpu features at runtime
  Config/Sample.cfg
  Source/API/EbSvtAv1.h
  Source/API/EbSvtAv1Dec.h
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncodeContext.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  gstreamer-plugin/gstsvtav1enc.c
  test/InvTxfm2dAsmTest.cc
  test/PsnrTest.cc
  test/RestorationPickTest.cc
  test/TestEnv.c
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
Labels: P1, simd

#868 Add missing palette size initialization in search_best_independent_uv_mode
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#841 Added residual_kernel16bit for SSE2, fix assigne pointers kernels
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/ResidualTest.cc
Labels: P1, simd

#854 fix deadlock in vbr mode:
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
Labels: bugfix

#863 fix assert failed when setting adaptive_quantization = 1 with debugging build
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
Labels: bugfix

#855 Enable AVX2 kernel eb_av1_fwd_txfm2d_32x16() to calculate DCT_DCT
  Source/Lib/Common/Codec/EbTransforms.c
  test/TxfmCommon.h
Labels: P1, simd

#880 remove assert for highbd intra prediction AVX2
  Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
Labels: bugfix

#871 CI: Create initial GitHub Actions workflow
  .github/workflows/svt-av1.yml
Labels: ci

#872 Implementation of function av1_k_means_dim1, av1_k_means_dim2 for AVX2
  Source/Lib/Common/ASM_AVX2/palette_avx2.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Common/Codec/k_means_template.h
  Source/Lib/Common/Codec/palette.c
  test/PaletteModeUtilTest.cc
Labels: P1, S+, simd

#883 Enhanced M0 Settings
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+

#870 fix cra for altref
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: bugfix

#874 [SIMD] Update eb_av1_wiener_convolve_add_src AVX2 and add AVX512
  Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
  Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/synonyms_avx2.h
  Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.h
  Source/Lib/Common/ASM_AVX512/convolve_avx512.h
  Source/Lib/Common/ASM_AVX512/wiener_convolve_avx512.c
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Common/Codec/convolve.c
  test/weiner_convolve_test.cc
  test/wiener_convolve_test.cc
Labels: P1, blocker, simd

#876 Cleanup Phase II
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbCodingLoop.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbMcp.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: Cleanup

#882 10bit opt
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+, enhancement

#878 Tx_size search_early_exit
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, S+

#869 Add 10bit test to Travis
  .travis.yml
Labels: travis

#881 Rate est update
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbMdRateEstimation.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbUtility.c
Labels: P1, Q+, blocker, enhancement

#814 RPS clean up and improvements
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPredictionStructure.c
Labels: P1, blocker, new feature

#894 Initial version of decoder with multi-thread support
  CHANGELOG.md
  Source/API/EbSvtAv1Dec.h
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbDecParamParser.h
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbSystemResourceManager.c
  Source/Lib/Common/Codec/EbSystemResourceManager.h
  Source/Lib/Common/Codec/EbTime.c
  Source/Lib/Common/Codec/EbTime.h
  Source/Lib/Decoder/Codec/EbDecCdef.c
  Source/Lib/Decoder/Codec/EbDecCdef.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecLF.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecNbr.c
  Source/Lib/Decoder/Codec/EbDecNbr.h
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecObmc.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseFrame.c
  Source/Lib/Decoder/Codec/EbDecParseFrame.h
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbDecProcess.h
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecRestoration.c
  Source/Lib/Decoder/Codec/EbDecRestoration.h
  Source/Lib/Decoder/Codec/EbDecSuperRes.c
  Source/Lib/Decoder/Codec/EbDecUtils.c
  Source/Lib/Decoder/Codec/EbDecUtils.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: S+, decoder

#900 Remove warnings in MacOS
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  test/CdefTest.cc
  test/GlobalMotionUtilTest.cc
  test/PaletteModeUtilTest.cc
  test/PictureOperatorTest.cc
  test/ResidualTest.cc
  test/SadTest.cc
  test/SpatialFullDistortionTest.cc
  test/TxfmCommon.h
Labels: build

#901 Update the signal presets
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPredictionStructure.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: P1, Q+, blocker

#904 address issue #546 and disable AVX512 by default
  Source/Lib/Common/ASM_SSE2/EbDeblockingFilter_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbDeblockingFilter_SSE2.h
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDeblockingFilter.h
  Source/Lib/Common/Codec/EbDefinitions.h
  test/DeblockTest.cc
  test/loopfilter_ref.h
Labels: Cleanup, simd

#903 Fix valgrind issue in eb_av1_selfguided_restoration_avx2()
  Source/Lib/Common/ASM_AVX2/selfguided_avx2.c
Labels: bugfix

#849 Adds parameter vbv-bufsize to CVBR mode
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Rate Control

#907 Cleanup some unused functions and detectors
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.h
Labels: Cleanup

#913 Fixes for update_av1_mi_map() and update_mi_map() valgrind errors
  Source/Lib/Common/Codec/EbModeDecision.c
Labels: bugfix

#914 Github Actions CI: Add build matrix
  .github/workflows/svt-av1.yml
Labels: ci

#915 Macro cleanup
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbMdRateEstimation.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPredictionStructure.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecUtils.h
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: Cleanup

#825 remove useless Fifo* in EbEncHandle.
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbDlfProcess.c
  Source/Lib/Common/Codec/EbDlfProcess.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.h
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.h
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateControlProcess.h
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Common/Codec/EbRestProcess.h
  Source/Lib/Common/Codec/EbRestorationPick.c
  Source/Lib/Common/Codec/EbSystemResourceManager.c
  Source/Lib/Common/Codec/EbSystemResourceManager.h
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbDecProcess.h
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCdefProcess.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbEncHandle.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.h
Labels: Cleanup, P2

#906 asm: fix build for nasm
  Source/Lib/Common/ASM_SSE2/CMakeLists.txt
  Source/Lib/Common/ASM_SSSE3/CMakeLists.txt
Labels: build

#809 add svt log system
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbFileUtils.c
  Source/App/DecApp/EbMD5Utility.c
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbBitstreamUnit.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbLog.c
  Source/Lib/Common/Codec/EbLog.h
  Source/Lib/Common/Codec/EbMalloc.c
  Source/Lib/Common/Codec/EbMalloc.h
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/grainSynthesis.c
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbObuParse.h
  Source/Lib/Encoder/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/synonyms_avx2.h
  Source/Lib/Encoder/ASM_AVX512/synonyms_avx512.h
  Source/Lib/Encoder/Codec/EbCdef.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestoration.c
  Source/Lib/Encoder/Codec/EbRestorationPick.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbTransforms.c
  Source/Lib/Encoder/Codec/corner_match.c
  Source/Lib/Encoder/Codec/noise_model.c
  Source/Lib/Encoder/Codec/noise_util.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P2

#924 EbAppConfig: Don't call fclose on error_log_file if it's equal to stderr
  Source/App/EncApp/EbAppConfig.c
Labels: bugfix

#926 use optimized version for convolve intraBC
  Source/Lib/Encoder/Codec/EbInterPrediction.c
Labels: bugfix, simd
