Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-11, with the labels that each got.

#753 Document TargetBitRate
  Docs/svt-av1_encoder_user_guide.md
Labels: documentation

#761 Memory leak fix
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
Labels: P1, bugfix

#694 [SIMD] Update sad and get_eight_horizontal_search_point_results avx2
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/Codec/EbComputeSAD.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  test/SadTest.cc
Labels: P1, S+, simd

#763 Fix the r2r which is caused by tx search in encdec
  Source/Lib/Common/Codec/EbFullLoop.c
Labels: P1, bugfix

#762 A/B shape skip based on SQ/H/V shape costs
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, S+, enhancement

#725 [SIMD] Add combined_averaging_ssd_avx512() and eb_av1_txb_init_levels_avx512()
  Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Inline_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
  Source/Lib/Common/ASM_AVX2/encodetxb_avx2.c
  Source/Lib/Common/ASM_AVX512/EbCombinedAveragingSAD_AVX512.c
  Source/Lib/Common/ASM_AVX512/encodetxb_avx512.c
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Common/ASM_SSE4_1/EbMemory_SSE4_1.h
  Source/Lib/Common/Codec/EbComputeSAD.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/EncodeTxbAsmTest.cc
  test/SadTest.cc
Labels: P1, S+, simd

#684 Add eb_cdef_filter_block_8x8_16_avx512() and search_one_dual_avx512()
  Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
  Source/Lib/Common/ASM_AVX2/cdef_block_avx2.c
  Source/Lib/Common/ASM_AVX2/cdef_block_simd.c
  Source/Lib/Common/ASM_AVX2/v256_intrinsics_x86.h
  Source/Lib/Common/ASM_AVX512/EbCdef_AVX512.c
  Source/Lib/Common/ASM_AVX512/cdef_block_avx512.c
  Source/Lib/Common/ASM_SSE2/v128_intrinsics_x86.h
  Source/Lib/Common/ASM_SSE2/v64_intrinsics_x86.h
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCdef.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/CdefTest.cc
Labels: P1, S+, simd

#764 Fix temporal filtering for non-key Intra frames
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: P1, Q+, bugfix

#756 Add OBMC SAD unit test
  test/OBMCSadTest.cc
Labels: P2, test

#757 Add OBMC variance unit test
  test/OBMCVarianceTest.cc
Labels: P2, test

#744 Palette
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbMdRateEstimation.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/k_means_template.h
  Source/Lib/Common/Codec/palette.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: API Change, P1, Q+, new feature

#769 Interpolation filter search for 10-bit (#769)
  Source/Lib/Common/Codec/EbInterPrediction.c
Labels: P1, new feature

#774 Fix R2R issues
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#758 Sample commands
  Docs/svt-av1_encoder_user_guide.md
Labels: P2, documentation

#784 added sliding windows for 2 pass cutree
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbReferenceObject.h
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
Labels: P1, Q+

#747 Fix non-8 aligned gop size
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: P1, blocker, bugfix

#770 hbd clean up
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, enhancement

#794 EbAppConfig: fix jump depends on uninitialized value
  Source/App/EncApp/EbAppConfig.c
Labels: P1, bugfix

#788 Adaptive Open Loop Partitioning
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, S+

#792 Fix : decoder 12-bit output mismatch
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
Labels: P1, decoder

#768 Fix the corruption in M3(resolution like 1080P)
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: P2, bugfix

#803 Remove duplicated implementation of warp_plane for high bit depth
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbWarpedMotion.c
  Source/Lib/Common/Codec/EbWarpedMotion.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
Labels: Cleanup, P1

#802 Fix mismatch between C and AVX2 kernel get_eight_horizontal_search_po…
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  test/SadTest.cc
Labels: P1, bugfix, simd

#806 Fix mismatch between C and SSE4, AVX2 for sad_loop_kernel_sparse
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
Labels: P1, simd

#805 ffmpeg: fix assert in avcodec_receive_packet
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: P1, ffmpeg

#796 Fix issue in unit test: DeblockTest
  Source/Lib/Common/ASM_SSE2/EbDeblockingFilter_Intrinsic_SSE2.c
Labels: P1, bugfix

#781 Fix issue in unit test: ResidualSumTest.MatchTest/4,13 and 14
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
Labels: P1, test

#782 fixed referenced_area sb_index boundary check for 2 pass
  Source/Lib/Common/Codec/EbCodingLoop.c
Labels: P1, Q+

#804 Bug fixes
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#816 Turn OFF NON_KF_INTRA_TF_FIX pending fixing issue 710
  Source/Lib/Common/Codec/EbDefinitions.h
Labels: P1, blocker

#797 10bit rdoq
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+

#818 Improve High-Precision MV
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
Labels: P1, Q+, bugfix

#810 EbPictureControlSet: fix rst_frame leak
  Source/Lib/Common/Codec/EbPictureControlSet.c
Labels: P1, bugfix

#827 Remove EbAvcStyleMcp source and header files
  Source/Lib/Common/Codec/EbAvcStyleMcp.c
  Source/Lib/Common/Codec/EbAvcStyleMcp.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  test/AVCStyleMcpTest.cc
Labels: Cleanup, P2

#828 10bit ii comp atb
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/sse_avx2.c
  Source/Lib/Common/ASM_SSE2/highbd_subtract_sse2.c
  Source/Lib/Common/ASM_SSSE3/reconinter_ssse3.c
  Source/Lib/Common/C_DEFAULT/EncodeTxbRef_C.c
  Source/Lib/Common/C_DEFAULT/EncodeTxbRef_C.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbMeSadCalculation.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  third_party/fastfeat/fast.c
Labels: P1, Q+

#820 Encoder Mode 0 optimization
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: P1, Q+, S+, blocker

#832 Update cost calculation for cdef filtering
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCdefProcess.c
Labels: P1, Q+
