Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-06, with the labels that each got.

#325 Rdoq tx
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbTransforms.h
Labels: P1, Q+

#313 sequence level data staructure is harmonizaed between encoder and decoder
  Source/API/EbSvtAv1.h
  Source/API/EbSvtAv1Dec.h
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbCdefProcess.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbDlfProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Common/Codec/EbString.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/RateControlModel.c
  Source/Lib/Common/Codec/av1me.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecStruct.h
  Source/Lib/Decoder/Codec/EbObuParse.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Cleanup

#327 Alt-ref all modes
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+

#339 Improved_NSQ_M0
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+

#328 M0 mr intra pred
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: P1, Q+

#338 Bug fixes related to Chroma and 64x64 block size
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+, bug

#333 [SIMD] Wiener Filter AVX2
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Common/ASM_AVX2/pickrst_avx2.h
  Source/Lib/Common/ASM_AVX2/transpose_avx2.h
  Source/Lib/Common/Codec/EbRestorationPick.c
  test/CMakeLists.txt
  test/EbUnitTest.h
  test/EbUnitTestUtility.c
  test/EbUnitTestUtility.h
  test/RestorationPickTest.cc
Labels: P1, S+, simd

#342 Decoder Bug fix in Mac/Linux platform
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
Labels: bug

#341 FL Quant
  Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbDlfProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
Labels: P1, Q+

#336 [Bug fix] filtering strength adjustment for Alt-ref tool
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/EbTemporalFiltering.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+, enhancement

#347 Statistics report functionality
  CHANGELOG.md
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1.h
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, new feature

#352 Turn on NSQ_ME_OPT by default
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
Labels: P1, S+, bug, simd

#337 Adding support for segmentation
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbCabacContextModel.c
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateControlProcess.h
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/EbSegmentation.h
  Source/Lib/Common/Codec/EbSegmentationParams.h
  Source/Lib/Common/Codec/EbTransforms.h
  Source/Lib/Decoder/Codec/EbDecStruct.h
  Source/Lib/Decoder/Codec/EbObuParse.h
  Source/Lib/Encoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, new feature

#353 Downsampling filtering
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.h
  Source/Lib/Common/Codec/EbReferenceObject.c
  Source/Lib/Common/Codec/EbReferenceObject.h
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+

#284 EbDefinitions: Don't redefine fseeko64 and ftello64
  Source/Lib/Common/Codec/EbDefinitions.h
Labels: Cleanup

#287 EB_MALLOC: remove duplicate code and do more check
  Source/Lib/Common/Codec/EbDefinitions.h
Labels: bug, memory

#356 EB_MALLOC: remove duplicate code and do more check
  Source/Lib/Common/Codec/EbDefinitions.h
Labels: Cleanup

#360 cleanup: remove trailing whitespace and convert tab to four spaces
  .gitignore
  .travis.yml
  Build/windows/build.bat
  CHANGELOG.md
  CMakeLists.txt
  Config/Sample.cfg
  Docs/svt-av1_decoder_user_guide.md
  Docs/svt-av1_encoder_user_guide.md
  NOTICES.md
  STYLE.md
  Source/Lib/Common/ASM_AVX2/CMakeLists.txt
  Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c
  Source/Lib/Common/ASM_SSE2/CMakeLists.txt
  Source/Lib/Common/ASM_SSE2/x64Macro.asm
  Source/Lib/Common/ASM_SSE4_1/CMakeLists.txt
  Source/Lib/Common/ASM_SSSE3/CMakeLists.txt
  Source/Lib/Common/CMakeLists.txt
  Source/Lib/Common/C_DEFAULT/CMakeLists.txt
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/Codec/EbEncHandle.c
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  ffmpeg_plugin/README.md
  gstreamer-plugin/README.md
  gstreamer-plugin/meson.build
  test/.clang-format
  test/CMakeLists.txt
  test/Readme.md
  test/api_test/CMakeLists.txt
  test/api_test/SvtAv1EncApiTest.cc
  test/e2e_test/CMakeLists.txt
  test/e2e_test/FrameQueue.h
  test/e2e_test/RefDecoder.h
  test/vectors/conformance_test.cfg
  test/vectors/smoking_test.cfg
  test/vectors/video_src.cfg
Labels: Cleanup, P1

#355 Fix gcc compiler errors
  Source/Lib/Common/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/Codec/EbInterPrediction.c
Labels: build, simd

#372 Fix implicit declaration, avoid compile-time overflow, use correct time functions
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbSegmentation.c
Labels: build

#319 Travis CI: Remove allow_failure from Style job
  .travis.yml
Labels: P1, test

#348 [SIMD] Add HandleTransform AVX2
  Source/Lib/Common/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
  Source/Lib/Common/Codec/EbTransforms.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/InvTxfm2dAsmTest.cc
  test/TxfmCommon.h
Labels: P1, S+, simd

#330 Improved sub-pel refinement
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: P1, Q+, enhancement

#354 Weiner filter avx2 bug fix
  Source/Lib/Common/ASM_AVX2/pickrst_avx2.c
Labels: P1, bug, simd

#359 Simd quantize fp
  Source/Lib/Common/ASM_AVX2/av1_quantize_avx2.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/QuantAsmTest.cc
  test/RestorationPickTest.cc
  test/quantize_func_test.cc
Labels: P1, S+, simd

#375 Cleanup trailing spaces
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
Labels: Cleanup, P1

#361 markdown: format markdown files
  CHANGELOG.md
  CONTRIBUTING.md
  Docs/svt-av1_decoder_user_guide.md
  Docs/svt-av1_encoder_user_guide.md
  LICENSE.md
  NOTICES.md
  README.md
  STYLE.md
  ffmpeg_plugin/README.md
  gstreamer-plugin/README.md
  test/Readme.md
Labels: Cleanup, documentation

#350 Add more param test into api_test
  CMakeLists.txt
  Source/Lib/Encoder/Codec/CMakeLists.txt
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
Labels: test

#276 Cmakelists: redo the lists.
  .travis.yml
  CMakeLists.txt
  Source/App/DecApp/CMakeLists.txt
  Source/App/EncApp/CMakeLists.txt
  Source/Lib/Common/ASM_AVX2/CMakeLists.txt
  Source/Lib/Common/ASM_SSE2/CMakeLists.txt
  Source/Lib/Common/ASM_SSE4_1/CMakeLists.txt
  Source/Lib/Common/ASM_SSSE3/CMakeLists.txt
  Source/Lib/Common/C_DEFAULT/CMakeLists.txt
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/Codec/CMakeLists.txt
  Source/Lib/Decoder/pkg-config.pc.in
  Source/Lib/Encoder/CMakeLists.txt
  Source/Lib/Encoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/pkg-config.pc.in
  gstreamer-plugin/CMakeLists.txt
  test/CMakeLists.txt
  test/api_test/CMakeLists.txt
  test/e2e_test/CMakeLists.txt
  test/e2e_test/libaom_dependency.cmake
  test/e2e_test/test_data_download_worker.cmake
  test/e2e_test/test_data_util.cmake
  third_party/googletest/CMakeLists.txt
Labels: P1, build

#301 Cherry pick bug fixes in SVT-HEVC
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
Labels: P1, bug, simd

#389 Incomplete SBs fix (rebased)
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+

#286 Enable SVT-AV1 mp4 and mkv/webm container support
  Source/API/EbSvtAv1Enc.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: ffmpeg

#345 Fix _mm256_setr_m128i related GNUC bug
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
Labels: P1, bug, simd

#376 CI: Add binary identicality test to Travis
  .travis.yml
Labels: ci

#410 travis: Fix Binary Identical test
  .travis.yml
Labels: ci

#409 De-coupled completely the HME/ME/Subpel used for ME Inter prediction …
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
Labels: Cleanup, P1

#404 QP Scaling Tuning
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
Labels: P1, Q+

#418 Fix warnings for all platforms/compilers
  Source/API/EbSvtAv1Dec.h
  Source/App/DecApp/EbDecAppMain.c
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppInputy4m.c
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.h
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbMotionEstimationContext.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRestorationPick.c
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/EbSegmentation.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/EbTransforms.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/RateControlModel.c
  Source/Lib/Common/Codec/noise_model.c
  Source/Lib/Decoder/Codec/EbDecBitstream.c
  Source/Lib/Decoder/Codec/EbDecBitstream.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecNbr.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbObuParse.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Cleanup, P1
