Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-07, with the labels that each got.

#364 Add SOVERSION for Encoder and Decoder shared libraries
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Encoder/CMakeLists.txt
Labels: build

#421 Travis: Add Werror CFLAG when building SVT-AV1
  .travis.yml
Labels: build

#396 pkg-config: set version to 0.6.0 instead of 1.3.0
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/pkg-config.pc.in
  Source/Lib/Encoder/CMakeLists.txt
  Source/Lib/Encoder/pkg-config.pc.in
Labels: P1, build

#426 Fix chroma artifacts in high density presets
  Source/Lib/Common/Codec/EbCodingLoop.c
Labels: P1, blocker, bug

#413 sc detector tuning
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
Labels: P1

#384 [SIMD] Port warp_plane_avx2.c from aom
  Source/Lib/Common/ASM_AVX2/warp_plane_avx2.c
  Source/Lib/Common/Codec/EbWarpedMotion.c
  Source/Lib/Common/Codec/EbWarpedMotion.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/frame_error_test.cc
  test/random.h
  test/warp_filter_test.cc
  test/warp_filter_test_util.cc
  test/warp_filter_test_util.h
Labels: simd

#411 Add unit test for interpolation in inter prediction
  Source/Lib/Common/Codec/EbInterPrediction.c
  test/convolve_2d_funcs.h
  test/convolve_2d_test.cc
Labels: P1, test

#420 Add more e2e test and remove compiling warnings in test
  test/BitstreamWriterTest.cc
  test/FwdTxfm1dTest.cc
  test/FwdTxfm2dTest.cc
  test/InvTxfm1dTest.cc
  test/InvTxfm2dAsmTest.cc
  test/QuantAsmTest.cc
  test/RestorationPickTest.cc
  test/TxfmCommon.h
  test/api_test/SvtAv1EncApiTest.cc
  test/api_test/params.h
  test/e2e_test/E2eTestVectors.h
  test/e2e_test/FrameQueue.cc
  test/e2e_test/ParseUtil.cc
  test/e2e_test/RefDecoder.cc
  test/e2e_test/RefDecoder.h
  test/e2e_test/SvtAv1E2EFramework.cc
  test/e2e_test/SvtAv1E2EFramework.h
  test/e2e_test/SvtAv1E2EParamsTest.cc
  test/e2e_test/SvtAv1E2ETest.cc
  test/e2e_test/VideoSource.cc
  test/e2e_test/Y4mVideoSource.cc
  test/e2e_test/test_vector_list.txt
  test/quantize_func_test.cc
  test/ref/TxfmRef.cc
Labels: test

#427 appveyor: Fix artifacts
  appveyor.yml
Labels: build, ci

#435 Use unaligned load commands in the intrinsics intra prediction kernels
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSE2/EbIntraPrediction_AV1_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c
Labels: blocker, bug

#438 Remove build warning in unit test
  test/BitstreamWriterTest.cc
  test/CMakeLists.txt
  test/EbUnitTestUtility.c
  test/FwdTxfm1dTest.cc
  test/FwdTxfm2dAsmTest.cc
  test/FwdTxfm2dTest.cc
  test/InvTxfm1dTest.cc
  test/InvTxfm2dAsmTest.cc
  test/QuantAsmTest.cc
  test/convolve_2d_test.cc
  test/e2e_test/CMakeLists.txt
  test/e2e_test/E2eTestVectors.h
  test/e2e_test/FrameQueue.cc
  test/e2e_test/ParseUtil.cc
  test/e2e_test/RefDecoder.cc
  test/e2e_test/SvtAv1E2EFramework.cc
  test/e2e_test/SvtAv1E2EParamsTest.cc
  test/e2e_test/VideoSource.cc
  test/intrapred_cfl_test.cc
  test/intrapred_dr_test.cc
  test/intrapred_edge_filter_test.cc
  test/intrapred_test.cc
  test/warp_filter_test_util.cc
Labels: build, test

#429 Initial decoder version with inter tools support
  CHANGELOG.md
  Docs/svt-av1_decoder_user_guide.md
  Source/App/DecApp/EbDecAppMain.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecNbr.c
  Source/Lib/Decoder/Codec/EbDecNbr.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.h
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecStruct.h
  Source/Lib/Decoder/Codec/EbDecUtils.c
  Source/Lib/Decoder/Codec/EbDecUtils.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: P1, enhancement

#377 [SIMD] Port av1_inv_txfm_avx2.c from aom
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/txfm_common_avx2.h
  Source/Lib/Common/ASM_SSE4_1/av1_fwd_txfm1d_sse4.c
  Source/Lib/Common/ASM_SSE4_1/av1_txfm_sse4.h
  Source/Lib/Common/ASM_SSE4_1/highbd_fwd_txfm_sse4.c
  Source/Lib/Common/ASM_SSE4_1/highbd_inv_txfm_sse4.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbTransforms.c
  Source/Lib/Common/Codec/EbTransforms.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/InvTxfm2dAsmTest.cc
  test/ref/TxfmRef.h
Labels: P1, simd

#443 travis: Fix Werror, set os and compiler for BinIden
  .travis.yml
Labels: build, ci

#445 Improve Temporal Filtering
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/EbTemporalFiltering.h
Labels: P1, Q+

#394 [SIMD] Add spatial_full_distortion_kernel_avx2()
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  test/SpatialFullDistortionTest.cc
Labels: P1, blocker, simd

#434 Fix the stability issue caused by BRC
  Source/Lib/Common/Codec/EbRateControlProcess.c
Labels: P1, bug

#450 10 bit path for Mode Decision: intra part
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.h
  Source/Lib/Common/C_DEFAULT/EbComputeSAD_C.c
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingLoop.h
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbComputeSAD.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbNeighborArrays.c
  Source/Lib/Common/Codec/EbNeighborArrays.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  test/SpatialFullDistortionTest.cc
Labels: P1, Q+

#454 remove settings asmtype to 0 to use sse4 code instead of c code in te…
  Source/Lib/Common/Codec/EbTemporalFiltering.c
Labels: Cleanup, bug

#452 Fix different outputs between Windows and Linux
  Source/Lib/Common/Codec/EbDefinitions.h
Labels: P1, bug

#393 Harmonized frame level data structure between encoder and decoder
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCdefProcess.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPacketizationReorderQueue.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/RateControlModel.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecStruct.h
Labels: Cleanup, P2

#432 Frame end CDF update
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncodeContext.c
  Source/Lib/Common/Codec/EbEncodeContext.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbMdRateEstimation.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureDemuxResults.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbPictureManagerQueue.h
  Source/Lib/Common/Codec/EbReferenceObject.h
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+, new feature

#456 Add unit test for cdef
  test/CdefTest.cc
  test/SpatialFullDistortionTest.cc
Labels: Cleanup, test

#444 Fix assembly implementation of sad_loop_kernel_sparse
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
Labels: bug

#412 Interpred tools test
  Source/Lib/Common/C_DEFAULT/EbComputeSAD_C.c
  Source/Lib/Common/C_DEFAULT/EbComputeSAD_C.h
  test/SadTest.cc
  test/VarianceTest.cc
  test/compute_mean_test.cc
  test/ref/EbComputeMean_C.c
  test/subtract_avg_cfl_test.cc
Labels: P1, test

#458 Fix saturate issue in hme sad
  Source/Lib/Common/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
Labels: P1, bug

#484 Fix for logical processors being ignored on macOS
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: bug

#460 Bug fixing for intrapred unit test
  test/intrapred_test.cc
Labels: test

#457 Improve SIMD alignment
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimationContext.c
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbRestorationPick.c
  Source/Lib/Common/Codec/EbWarpedMotion.c
  Source/Lib/Common/Codec/EbWarpedMotion.h
Labels: P1, simd

#461 re-write sequence header parser
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecParseObuUtil.h
  test/e2e_test/CMakeLists.txt
  test/e2e_test/ParseUtil.cc
  test/e2e_test/ParseUtil.h
  test/e2e_test/RefDecoder.h
Labels: decoder

#442 [SIMD] Add transpose_8bit_16x16_reg128bit_avx2()
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/transpose_avx2.h
  Source/Lib/Common/ASM_SSE2/transpose_sse2.h
  test/TransposeTest.cc
Labels: P1, S+, simd

#479 Remove verbose warning message during build
  Build/linux/build.sh
Labels: P1, build

#487 Add longtime conformance test
  test/e2e_test/SvtAv1E2ETest.cc
  test/e2e_test/VideoSource.cc
  test/e2e_test/Y4mVideoSource.cc
  test/e2e_test/YuvVideoSource.cc
  test/vectors/longtime_comformance_test.cfg
Labels: P2, test

#489 add more unit tests for sad functions
  test/SadTest.cc
Labels: P2, test

#492 Optimizing interp_cubic(). Precalculated data added. Work ~5 times fa…
  Source/Lib/Common/Codec/EbInterPrediction.c
Labels: enhancement

#474 Add unit test for project-related test in selfguided restoration
  test/SelfGuidedUtilTest.cc
Labels: P2, test

#498 Add FFT and iFFT unit test
  test/FFTTest.cc
  test/random.h
Labels: P1, test

#472 Added Temporal MV scan support in decoder and Decoder bug fixes in Inter path
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbCabacContextModel.c
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Decoder/Codec/EbDecBitReader.c
  Source/Lib/Decoder/Codec/EbDecBitReader.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.h
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecUtils.c
  Source/Lib/Decoder/Codec/EbDecUtils.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: P1, decoder

#431 Set compiling option to SSE4.1
  CMakeLists.txt
Labels: P1, build

#462 Fix encoder parameter setup issue in e2e test
  test/e2e_test/E2eTestVectors.h
  test/e2e_test/RefDecoder.cc
  test/e2e_test/RefDecoder.h
  test/e2e_test/SvtAv1E2EFramework.cc
  test/e2e_test/SvtAv1E2EFramework.h
  test/e2e_test/SvtAv1E2EParamsTest.cc
  test/e2e_test/SvtAv1E2ETest.cc
Labels: test

#499 Fix crash when using free() to release memory created by _aligned_mal…
  Source/Lib/Common/Codec/EbMotionEstimationContext.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbRestProcess.c
Labels: bug

#476 Fix test failure in GetEightSadTest
  test/SadTest.cc
Labels: P1, bug

#459 Simplify CMake Flag checkers
  Source/Lib/Common/ASM_AVX2/CMakeLists.txt
  Source/Lib/Common/ASM_AVX512/CMakeLists.txt
  Source/Lib/Common/ASM_SSE2/CMakeLists.txt
  Source/Lib/Common/ASM_SSE4_1/CMakeLists.txt
  Source/Lib/Common/ASM_SSSE3/CMakeLists.txt
  Source/Lib/Common/CMakeLists.txt
Labels: P1, build
