Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-05, with the labels that each got.

#196 Add aom_highbd_paeth_predictor kernel in AVX2.
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
Labels: P2, S+

#201 Fix return values check for TerminateThread, ReleaseSemaphore, CloseHandle and ReleaseMutex
  Source/Lib/Common/Codec/EbThreads.c
Labels: P2

#229 Replace with the correct mutex
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
Labels: bug

#242 Memory optimizations for all resolutions
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingLoop.h
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncodeContext.c
  Source/Lib/Common/Codec/EbEncodeContext.h
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationContext.c
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
  Source/Lib/Common/Codec/EbMotionEstimationLcuResults.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionQueue.h
  Source/Lib/Common/Codec/EbReferenceObject.h
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.h
  Source/Lib/Common/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Common/Codec/EbSourceBasedOperationsProcess.h
  Source/Lib/Common/Codec/EbThreads.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbEncHandle.h
Labels: Cleanup, P1, memory

#213 Fix a regression which increases init time
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P2, S+

#211 Update table Subsampled_Size
  Source/Lib/Common/Codec/EbUtility.h
Labels: P1, new feature

#264 Switch CMake release builds to -O3
  CMakeLists.txt
Labels: P1, S+

#216 Use prefix for asm files using AOM's method, add a note about macOS fd limit
  README.md
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.asm
  Source/Lib/Common/ASM_SSE2/x64RegisterUtil.asm
  Source/Lib/Common/ASM_SSE2/x64inc.asm
  Source/Lib/Common/Codec/EbThreads.c
Labels: Cleanup, P2

#243 Eighth pel
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
Labels: P1, Q+

#246 First version of Intra only decoder
  Docs/svt-av1_decoder_user_guide.md
  Source/API/EbSvtAv1.h
  Source/API/EbSvtAv1Dec.h
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbDecParamParser.h
  Source/App/DecApp/EbFileUtils.c
  Source/App/DecApp/EbFileUtils.h
  Source/App/DecApp/EbMD5Utility.c
  Source/App/DecApp/EbMD5Utility.h
  Source/Lib/Common/Codec/EbBitstreamUnit.h
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecBitReader.c
  Source/Lib/Decoder/Codec/EbDecBitReader.h
  Source/Lib/Decoder/Codec/EbDecBitstream.c
  Source/Lib/Decoder/Codec/EbDecBitstream.h
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.c
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecNbr.c
  Source/Lib/Decoder/Codec/EbDecNbr.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseFrame.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.h
  Source/Lib/Decoder/Codec/EbDecProcessFrame.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecStruct.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: P1, new feature

#269 CI: Update AppVeyor to Visual Studio 2019
  README.md
  appveyor.yml
Labels: buid

#271 Tune Preset 8
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Labels: P1, S+

#280 Style: add syntax stuff for the code blocks in STYLE.md
  STYLE.md
Labels: Cleanup

#273 Travis: add mirror and use https
  .travis.yml
Labels: ci

#230 Add switches for batch file for windows. Add VS2019
  .gitignore
  Build/windows/build.bat
  Build/windows/generate_vs17.bat
  README.md
Labels: P3, buid

#279 [WIP] Implementation of Alt-Ref pictures v1 - temporal filtering use case
  CHANGELOG.md
  Config/Sample.cfg
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/ASM_SSE4_1/EbTemporalFiltering_constants.h
  Source/Lib/Common/ASM_SSE4_1/EbTemporalFiltering_sse4.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncodeContext.c
  Source/Lib/Common/Codec/EbEncodeContext.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimation.h
  Source/Lib/Common/Codec/EbMotionEstimationContext.c
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.h
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPacketizationReorderQueue.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionQueue.c
  Source/Lib/Common/Codec/EbPictureDecisionQueue.h
  Source/Lib/Common/Codec/EbPictureDecisionReorderQueue.h
  Source/Lib/Common/Codec/EbPictureDecisionResults.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbPictureManagerQueue.c
  Source/Lib/Common/Codec/EbPictureManagerQueue.h
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/EbTemporalFiltering.h
  Source/Lib/Common/Codec/EbTemporalFiltering_sse4.h
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/av1me.c
  Source/Lib/Common/Codec/av1me.h
  Source/Lib/Common/Codec/noise_util.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbEncHandle.h
Labels: P1, Q+, new feature

#293 [WIP] CI: Add coding style check to Travis, cleanup
  .travis.yml
Labels: ci

#282 Verify bitstream writer using svt_reader
  test/BitstreamReaderMock.cc
  test/BitstreamReaderMock.h
  test/BitstreamWriterTest.cc
  test/CMakeLists.txt
Labels: Cleanup

#307 Adaptive Transform Block for INTRA
  CHANGELOG.md
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbDlfProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbTransforms.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Common/Codec/noise_model.c
Labels: P1, Q+, new feature

#310 Adaptive QP scaling
  CHANGELOG.md
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbRateControlProcess.c
Labels: P1, enhancement

#311 Disable overlay pictures (used by the Alt-refs) by default
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: blocker, bug

#303 Decoder: Added support for Tiles and 10bit
  CHANGELOG.md
  Docs/svt-av1_decoder_user_guide.md
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbMD5Utility.c
  Source/Lib/Common/Codec/EbBitstreamUnit.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
Labels: P1, new feature
