Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-10, with the labels that each got.

#620 Support arbitrary picture size (non multiple of 8)
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, enhancement

#592 Optimizing kernels construct_best_sorted_arrays_md_stage_2/3
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, S+

#630 Fix quantization mismatch
  Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/QuantAsmTest.cc
Labels: P1, bug, simd

#649 eighth_pel_precision
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+, new feature

#648 ATB for INTER
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
Labels: P1, Q+, new feature

#670 Fix AVX512 build
  Source/Lib/Common/ASM_AVX512/pickrst_avx512.c
Labels: P1, blocker, build

#661 Fix Issue #547
  Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.c
  Source/Lib/Common/Codec/convolve.c
Labels: P1, bugfix, simd

#671 Added WARP_UPDATE flag and modified when warping is active
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
Labels: P1, Q+, enhancement

#667 Add 10-bit path to inter Mode Decision
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+

#674 RDOQ for CHROMA
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, Q+

#666 Fix the outdated code in the unit tests of AVX512 inverse transforms
  test/InversetransformTests.cc
Labels: P1, simd, test

#650 Add PSNR unit test
  test/PsnrTest.cc
  test/TestEnv.c
Labels: P2, test

#653 Add temporal filter test
  test/TemporalFilterTest.cc
Labels: P2, test

#702 Encoder / common files separation Stage 1
  Source/Lib/Common/Codec/EbAvailability.c
  Source/Lib/Common/Codec/EbAvailability.h
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCdefProcess.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.h
  Source/Lib/Encoder/Codec/EbInitialRateControlResults.c
  Source/Lib/Encoder/Codec/EbInitialRateControlResults.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.h
  Source/Lib/Encoder/Codec/EbString.c
  Source/Lib/Encoder/Codec/EbString.h
Labels: Cleanup, P1, blocker

#682 Set hbd-md true by default
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, config change

#679 Obmc
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_AVX2/aom_subpixel_8t_intrin_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/obmc_sad_avx2.c
  Source/Lib/Common/ASM_AVX2/obmc_variance_avx2.c
  Source/Lib/Common/ASM_SSE2/aom_subpixel_8t_sse2.asm
  Source/Lib/Common/ASM_SSE2/variance_sse2.c
  Source/Lib/Common/ASM_SSE4_1/EbBlend_a64_mask_sse4.c
  Source/Lib/Common/ASM_SSE4_1/obmc_variance_sse4.c
  Source/Lib/Common/ASM_SSSE3/aom_subpixel_bilinear_ssse3.asm
  Source/Lib/Common/ASM_SSSE3/variance_impl_ssse3.c
  Source/Lib/Common/ASM_SSSE3/x86_abi_support.asm
  Source/Lib/Common/C_DEFAULT/sad_av1.c
  Source/Lib/Common/C_DEFAULT/variance.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Common/Codec/av1me.c
  Source/Lib/Common/Codec/av1me.h
  Source/Lib/Common/Codec/convolve.c
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Q+, new feature

#706 Fix GCC 8 compile warning
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
Labels: P1, blocker, build

#711 Fix memory leak
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
Labels: P1, bugfix

#646 Travis: Add GCC 8 and GCC 9 builds, cleanup
  .travis.yml
Labels: P2, build

#716 NEW_NEAR & NEAR_NEW support
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: Q+, enhancement

#720 add hbd temporal filter test
  test/TemporalFilterTest.cc
Labels: P1, blocker, test

#714 Filter intra prediction
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_SSE4_1/filterintra_sse4.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: P1, Q+, new feature

#719 Add link to performance tracker website in README.md
  README.md
Labels: documentation

#726 Fix assertion fail
  Source/Lib/Common/Codec/EbPictureBufferDesc.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Decoder/Codec/EbDecMemInit.c
Labels: P1, bug

#723 add picture operator test
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h
  test/PictureOperatorTest.cc
Labels: P2, test

#705 10bit upgrade
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: P1, new feature

#700 Qp scaling tables
  Source/Lib/Common/Codec/EbRateControlProcess.c
Labels: P1, Q+, enhancement

#722 Add NSQ shape prediction
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Common/Codec/EbModeDecisionConfiguration.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbRateDistortionCost.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
Labels: P1, S+

#712 Fix valgrind error
  Source/Lib/Common/Codec/EbFullLoop.c
Labels: P1, bugfix

#741 More aggressive MD Exit TH for M0 non-SC
  Source/Lib/Common/Codec/EbEncDecProcess.c
Labels: P1, S+, enhancement

#717 CMake: Apply fortify source if stack protector is also on
  CMakeLists.txt
Labels: P1, build

#740 Fix run-to-run in hbd-md 1
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, blocker, bugfix

#737 Add missing IFFT functions for C version with corresponding tests
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Common/Codec/fft.c
  test/FFTTest.cc
Labels: P1, simd, test

#748 Add filter intra predictor unit test
  test/FilterIntraPredTest.cc
Labels: P1, test

#743 Add missing eb_aom_highbd_8_mse16x16 for C version with tests
  Source/Lib/Common/C_DEFAULT/variance.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/VarianceTest.cc
Labels: P1, simd, test

#752 Bug Fix: Reading from unnamed pipe
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppProcessCmd.c
Labels: P1, bugfix
