Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-03, with the labels that each got.

#136 Live Encode - Updated Presets [0 to 7]
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbApi.h
  Source/App/CMakeLists.txt
  Source/App/EbAppProcessCmd.c
  Source/Lib/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbCodingLoop.h
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncDecProcess.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbFullLoop.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbInterPrediction.c
  Source/Lib/Codec/EbIntraPrediction.c
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecision.h
  Source/Lib/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Codec/EbModeDecisionConfiguration.h
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.h
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationContext.h
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbPictureOperators.c
  Source/Lib/Codec/EbPredictionStructure.h
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbRateDistortionCost.c
  Source/Lib/Codec/EbRateDistortionCost.h
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbRestProcess.h
  Source/Lib/Codec/EbRestoration.c
  Source/Lib/Codec/EbRestorationPick.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
  Source/Lib/Codec/RateControlGopInfo.h
  Source/Lib/Codec/aom_dsp_rtcd.h
Labels: enhancement

#130 Fix build error with clang
  Source/Lib/ASM_SSE2/EbPictureOperators_SSE2.asm
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbThreads.h
Labels: bug

#167 Don't use AVX2 SAD on non-AVX2 target
  Source/Lib/Codec/EbComputeSAD.h
Labels: bug

#191 Add doxygen template to STYLE.md
  STYLE.md
Labels: P1

#148 Optimization the transformation in av1_fwd_txfm2d_64x64_avx2(),
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_fwd_txfm_avx2.c
Labels: P2

#193 RC: VBR (Mode 2) and CVBR (Mode 3) Rebase
  Config/Sample.cfg
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbInitialRateControlReorderQueue.c
  Source/Lib/Common/Codec/EbInitialRateControlReorderQueue.h
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPacketizationReorderQueue.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbPictureManagerQueue.h
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateControlProcess.h
  Source/Lib/Common/Codec/EbRateControlTables.c
  Source/Lib/Common/Codec/EbRateControlTables.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, Rate Control, new feature

#177 motion estimation restructuring
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMeSadCalculation.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationContext.h
Labels: P1

#190 travis: add a small encode/decode smoke test
  .travis.yml
Labels: P2

#204 Fix the conflict between RC modes
  Source/Lib/Common/Codec/EbRateControlProcess.c
Labels: P1, blocker

#195 GStreamer plugin
  .travis.yml
  Build/windows/generate_vs17.bat
  gstreamer-plugin/CMakeLists.txt
  gstreamer-plugin/README.md
  gstreamer-plugin/gstsvtav1enc.c
  gstreamer-plugin/gstsvtav1enc.h
  gstreamer-plugin/meson.build
Labels: P1
