Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-08, with the labels that each got.

#486 [FFmpeg Plugin] Fix several SVT AV1 plugin issues.
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: P1, ffmpeg

#501 Add AVX512 code for high_bd_dc predictor
  Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
  Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
  Source/Lib/Common/ASM_SSE2/EbHighbdIntraPrediction_SSE2.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/EbHighbdIntraPredictionTests.cc
  test/EbHighbdIntraPredictionTests.h
  test/EbUnitTest.h
Labels: P1, blocker, simd

#470 Refactor
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
Labels: Cleanup, P2

#477 dummy video source support in e2e test
  test/e2e_test/DummyVideoSource.h
  test/e2e_test/E2eTestVectors.h
  test/e2e_test/SvtAv1E2EFramework.cc
  test/e2e_test/SvtAv1E2ETest.cc
  test/e2e_test/VideoSource.cc
  test/e2e_test/VideoSource.h
Labels: P2, test

#488 Add unit test for in-loop filter
  test/DeblockTest.cc
  test/loopfilter_ref.h
Labels: P2, test

#495 Add AVX512 code for high bd forward transform
  Source/Lib/Common/ASM_AVX512/highbd_fwd_txfm_AVX512.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/ForwardtransformTests.cc
Labels: P1, blocker, simd

#439 [WIP] Address Valgrind errors
  .travis.yml
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
Labels: bug

#555 Remove Unused Functions/Kernels
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbTransforms_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/txfm_common_avx2.h
  Source/Lib/Common/ASM_SSE2/EbIntraPrediction_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbIntraPrediction_SSE2.h
  Source/Lib/Common/ASM_SSE2/EbInvTransform_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbTransforms_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbTransforms_SSE2.h
  Source/Lib/Common/ASM_SSE2/av1_txfm_sse2.h
  Source/Lib/Common/ASM_SSE2/txfm_common_sse2.h
  Source/Lib/Common/ASM_SSE4_1/EbIntraPrediction16bit_Intrinsic_SSE4_1.c
  Source/Lib/Common/ASM_SSE4_1/EbIntraPrediction_SSE4_1.h
  Source/Lib/Common/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c
  Source/Lib/Common/ASM_SSE4_1/EbTransforms_SSE4_1.h
  Source/Lib/Common/ASM_SSE4_1/av1_fwd_txfm1d_sse4.c
  Source/Lib/Common/ASM_SSE4_1/av1_txfm1d_sse4.h
  Source/Lib/Common/ASM_SSE4_1/highbd_fwd_txfm_sse4.c
  Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/EbIntraPrediction_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/EbIntraPrediction_SSSE3.h
  Source/Lib/Common/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/EbMcp_SSSE3.h
  Source/Lib/Common/ASM_SSSE3/EbTransforms_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/EbTransforms_SSSE3.h
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/C_DEFAULT/EbTransforms_C.h
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbMcp.h
  Source/Lib/Common/Codec/EbMcpTables.c
  Source/Lib/Common/Codec/EbPredictionUnit.c
  Source/Lib/Common/Codec/EbTransforms.c
  Source/Lib/Common/Codec/EbTransforms.h
  test/vectors/smoking_test.cfg
  test/vectors/video_src.cfg
  third_party/googletest/CMakeLists.txt
  third_party/googletest/docs/Pkgconfig.md
  third_party/googletest/docs/XcodeGuide.md
  third_party/googletest/docs/advanced.md
  third_party/googletest/test/googletest-output-test-golden-lin.txt
  third_party/googletest/xcode/Scripts/runtests.sh
Labels: Cleanup

#502 Added support for Screen content tools and OBMC in Decoder
  CHANGELOG.md
  Source/App/DecApp/EbDecAppMain.c
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecObmc.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecUtils.c
  Source/Lib/Decoder/Codec/EbDecUtils.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: P1, decoder

#528 dr_prediction_AVX2 perf and style improvements
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSE2/lpf_common_sse2.h
Labels: P1, simd

#544 Fix crash issue when speed control flag is enabled
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
Labels: bugfix

#550 Fix build issues in unittest
  .travis.yml
  test/CMakeLists.txt
  test/TransposeTest.cc
Labels: ci, test
