Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-04, with the labels that each got.

#198 Fix the 4K10bit crash
  Source/Lib/Common/Codec/EbPictureControlSet.h
Labels: P1, bug

#124 Optimization md_update_all_neighbour_arrays_multiple() by 30%
  Source/Lib/Common/Codec/EbNeighborArrays.c
  Source/Lib/Common/Codec/EbNeighborArrays.h
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P2

#95 Add 422/444 support at API level
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbCodingUnit.c
  Source/Lib/Common/Codec/EbDlfProcess.c
  Source/Lib/Common/Codec/EbDlfProcess.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbMcp.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbReferenceObject.c
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Common/Codec/EbRestProcess.h
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbTransQuantBuffers.c
  Source/Lib/Common/Codec/noise_model.c
  Source/Lib/Common/Codec/noise_model.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1
