Repository AOMediaCodec/SVT-AV1, pull requests merged in 2019-09, with the labels that each got.

#571 Post processing filter
  CHANGELOG.md
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbDecParamParser.h
  Source/App/DecApp/EbDecTime.c
  Source/App/DecApp/EbDecTime.h
  Source/App/DecApp/EbFileUtils.h
  Source/Lib/Common/Codec/EbBitstreamUnit.h
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbCdef.h
  Source/Lib/Common/Codec/EbCdefProcess.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDeblockingFilter.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbRestoration.h
  Source/Lib/Decoder/Codec/EbDecBitReader.c
  Source/Lib/Decoder/Codec/EbDecBitReader.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecCdef.c
  Source/Lib/Decoder/Codec/EbDecCdef.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.c
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecLF.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecRestoration.c
  Source/Lib/Decoder/Codec/EbDecRestoration.h
  Source/Lib/Decoder/Codec/EbDecStruct.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: decoder

#582 MFMV
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbReferenceObject.c
  Source/Lib/Common/Codec/EbReferenceObject.h
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbRestProcess.c
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Q+, enhancement

#586 MD Exit @ Inter Depth Decision
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: S+

#529 Removed memcpy before call av1_inv_transform_recon() in inv_transform_recon_copy()
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
  Source/Lib/Common/ASM_SSE4_1/highbd_inv_txfm_sse4.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbTransforms.c
  Source/Lib/Common/Codec/EbTransforms.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  test/InvTxfm2dAsmTest.cc
Labels: P1, S+, simd

#576 EbMalloc: return EB_ErrorInsufficientResources for thread/semaphore/mutex create fail
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMalloc.h
  Source/Lib/Common/Codec/EbThreads.h
Labels: bug, ffmpeg

#591 Fix missing inializations raised by clang memory santizers
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, bug

#504 Ffmpeg plugin fixes and improvements
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: ffmpeg

#595 Qp modulation
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Q+, enhancement

#594 Speed optimization
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
Labels: S+

#599 Add unit tests for spatial full distortion functions
  test/SpatialFullDistortionTest.cc
Labels: test

#530 Update convolve avx2 functions
  Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/highbd_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/highbd_jnt_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/jnt_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/pickrst_avx2.h
  Source/Lib/Common/ASM_AVX2/transpose_avx2.c
  Source/Lib/Common/ASM_AVX2/transpose_avx2.h
  Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.c
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Common/ASM_SSE2/v64_intrinsics_x86.h
  Source/Lib/Common/ASM_SSE4_1/EbMemory_SSE4_1.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbRestorationPick.c
  test/CMakeLists.txt
  test/TransposeTest.cc
  test/convolve_2d_test.cc
Labels: P1, simd

#480 Add sad64x, sad128x and sad128xMx4d AVX512 optimization
  Source/Lib/Common/ASM_AVX512/EbComputeSAD_AVX512.h
  Source/Lib/Common/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  test/MotionEstimationTest.cc
Labels: P1, simd

#597 Inter intra compound
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
Labels: Q+, new feature

#601 Add unit tests for picture addition functions
  test/PictureAdditionTest.cc
Labels: test

#610 QP fix for 10 bit coding
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbFullLoop.c
Labels: bugfix

#589 Add unit test for residual related functions
  Source/Lib/Common/.DS_Store
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  test/ResidualTest.cc
Labels: test

#611 Macro removal
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/cdef_block_simd.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbEncDecProcess.h
  Source/Lib/Common/Codec/EbEncodeContext.c
  Source/Lib/Common/Codec/EbEncodeContext.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbEntropyCoding.h
  Source/Lib/Common/Codec/EbEntropyCodingProcess.c
  Source/Lib/Common/Codec/EbEntropyCodingProcess.h
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbFullLoop.h
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbMdRateEstimation.c
  Source/Lib/Common/Codec/EbMdRateEstimation.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.h
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.c
  Source/Lib/Common/Codec/EbPacketizationProcess.h
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureDemuxResults.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbPictureManagerQueue.h
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbRateControlProcess.c
  Source/Lib/Common/Codec/EbRateDistortionCost.c
  Source/Lib/Common/Codec/EbReferenceObject.c
  Source/Lib/Common/Codec/EbReferenceObject.h
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/EbSequenceControlSet.c
  Source/Lib/Common/Codec/EbSequenceControlSet.h
  Source/Lib/Common/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/EbTemporalFiltering.h
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Cleanup

#612 Add unit tests for pack/unpack functions
  Source/Lib/Common/ASM_AVX2/EbPackUnPack_AVX2.h
  test/PackUnPackTest.cc
Labels: test

#511 Refactor & Fix all warnings
  Source/App/DecApp/EbDecParamParser.h
  Source/App/DecApp/EbFileUtils.h
  Source/App/DecApp/EbMD5Utility.h
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbComputeSAD.h
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbMotionEstimationProcess.c
  Source/Lib/Common/Codec/EbPredictionStructure.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
  Source/Lib/Common/Codec/EbSegmentation.c
  Source/Lib/Common/Codec/EbThreads.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  test/BitstreamWriterTest.cc
  test/SadTest.cc
  test/e2e_test/RefDecoder.cc
  test/e2e_test/SvtAv1E2EParamsTest.cc
  test/e2e_test/VideoFrame.h
Labels: Cleanup, P1

#552 CMake: Don't set default CMAKE_BUILD_TYPE if MSVC or Xcode
  CMakeLists.txt
Labels: P1, build

#614 Travis maintenance: Update build environments, FFmpeg
  .travis.yml
  ffmpeg_plugin/README.md
Labels: build

#619 Update codec name
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: Cleanup, P1

#565 Remove limitation of less than 16 Sockets
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, enhancement

#617 Change the MRP prediction references for non-reference frames
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureDecisionProcess.c
  Source/Lib/Common/Codec/EbPredictionStructure.c
Labels: P1, enhancement

#618 Align remaining 10b distortion function calls in MD
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: P1, bug

#615 fix leaks for encmode 0
  Source/Lib/Common/Codec/EbPictureControlSet.c
  Source/Lib/Common/Codec/EbReferenceObject.c
Labels: P1, bug

#558 MinGW: Enable MinGW support
  CMakeLists.txt
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/App/EncApp/EbTime.c
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbEntropyCoding.c
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbTime.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  test/EbUnitTestUtility.c
  test/e2e_test/FrameQueue.cc
  test/e2e_test/SvtAv1E2EFramework.cc
  third_party/aom/inc/aom/aom_codec.h
  third_party/aom/inc/aom/aom_integer.h
Labels: build

#254 script: redo build.sh
  Build/linux/build.sh
Labels: P1, build

#627 Fix bug in eb_enc_msb_un_pack2d_sse2_intrin
  Source/Lib/Common/ASM_SSE2/EbPackUnPack_Intrinsic_SSE2.c
Labels: P1, bug

#162 Port to FreeBSD and maybe more
  Source/Lib/Common/ASM_SSE2/EbMcp_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbTransforms_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/Codec/EbMalloc.c
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  gstreamer-plugin/CMakeLists.txt
  gstreamer-plugin/meson.build
Labels: P1, build

#554 Cmakelists: Cleanup the main list
  CMakeLists.txt
Labels: P1, build

#634 Remove ImproveSharpness Feature
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbFullLoop.c
  Source/Lib/Common/Codec/EbInitialRateControlProcess.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
  gstreamer-plugin/gstsvtav1enc.c
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
  test/e2e_test/SvtAv1E2ETest.cc
Labels: API Change, Cleanup, P1, blocker

#507 Style check: split git grep for trs, use git ls-tree, sed, don't use travis_terminate
  .travis.yml
Labels: P1, style

#515 Optimization kernel av1_cost_coeffs_txb()
  Source/Lib/Common/Codec/EbRateDistortionCost.c
Labels: P1, simd

#625 Fix mismatch issue in packmsb test
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  test/PackUnPackTest.cc
Labels: P1, bug

#626 Fix mismatch issue in PackUnpack unit test
  test/PackUnPackTest.cc
Labels: P2, test

#628 Fix mismatch issue in picture addition test
  test/PictureAdditionTest.cc
Labels: P2, test

#635 Remove some MSVC build warnings
  Source/Lib/Common/Codec/EbCodingLoop.c
  Source/Lib/Common/Codec/EbEncDecProcess.c
  Source/Lib/Common/Codec/EbModeDecisionProcess.c
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbProductCodingLoop.c
Labels: Cleanup, P1, build

#631 Refine transpose unit test to cover more functions
  Source/Lib/Common/ASM_AVX2/transpose_avx2.c
  Source/Lib/Common/ASM_AVX2/transpose_avx2.h
  Source/Lib/Common/ASM_SSE2/transpose_sse2.c
  Source/Lib/Common/ASM_SSE2/transpose_sse2.h
  test/CMakeLists.txt
  test/TransposeTest.cc
Labels: simd, test

#629 Add more aom_sad func test
  test/MotionEstimationTest.cc
Labels: P2, test

#637 Add unit tests for get nz map context functions
  test/EncodeTxbAsmTest.cc
  test/ref/EncodeTxbRef.h
Labels: P2, test

#638 Add YUV422 and YUV444 support unit tests in video source
  test/e2e_test/DummyVideoSource.h
  test/e2e_test/E2eTestVectors.h
  test/e2e_test/RefDecoder.cc
  test/e2e_test/SvtAv1E2EFramework.cc
  test/e2e_test/SvtAv1E2ETest.cc
  test/e2e_test/VideoFrame.h
  test/e2e_test/VideoSource.cc
  test/e2e_test/VideoSource.h
  test/e2e_test/Y4mVideoSource.cc
  test/e2e_test/YuvVideoSource.cc
Labels: P2, test

#639 Add high bit-depth variance unit test
  test/HbdVarianceTest.cc
Labels: P2, test

#609 Compound mode and Film Grain support in Decoder
  CHANGELOG.md
  Source/API/EbSvtAv1.h
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbDecParamParser.h
  Source/App/DecApp/EbFileUtils.c
  Source/App/DecApp/EbFileUtils.h
  Source/App/DecApp/EbMD5Utility.c
  Source/Lib/Common/ASM_AVX2/EbBlend_a64_mask_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c
  Source/Lib/Common/ASM_AVX2/synonyms_avx2.h
  Source/Lib/Common/ASM_AVX2/variance_avx2.c
  Source/Lib/Common/ASM_SSE4_1/EbBlend_a64_mask_sse4.c
  Source/Lib/Common/ASM_SSE4_1/EbBlend_sse4.h
  Source/Lib/Common/Codec/EbBlend_a64_mask.c
  Source/Lib/Common/Codec/EbCodingUnit.h
  Source/Lib/Common/Codec/EbDeblockingFilter.c
  Source/Lib/Common/Codec/EbDeblockingFilter.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbModeDecision.h
  Source/Lib/Common/Codec/EbTemporalFiltering.c
  Source/Lib/Common/Codec/aom_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecCdef.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecLF.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecObmc.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.h
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.h
  Source/Lib/Decoder/Codec/EbDecRestoration.c
  Source/Lib/Decoder/Codec/EbDecUtils.c
  Source/Lib/Decoder/Codec/EbDecUtils.h
  Source/Lib/Decoder/Codec/EbObuParse.h
Labels: P1, decoder, new feature

#623 Prep 0.7.0 tag
  CHANGELOG.md
  Source/API/EbSvtAv1.h
  Source/App/DecApp/EbDecAppMain.c
  Source/App/DecApp/EbDecParamParser.c
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Encoder/CMakeLists.txt
Labels: P1

#493 enable mcts or umv0 support
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Common/Codec/EbModeDecision.c
  Source/Lib/Common/Codec/EbMotionEstimation.c
  Source/Lib/Common/Codec/EbPictureControlSet.h
  Source/Lib/Common/Codec/EbPictureManagerProcess.c
  Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbEncHandle.c
Labels: P1, enhancement

#655 Appveyor: Add Werror to msvc builds
  Source/Lib/Common/Codec/EbDefinitions.h
  appveyor.yml
Labels: build, ci

#621 Remove warped_motion_prediction_md: almost a duplicate of warped_moti…
  Source/Lib/Common/Codec/EbInterPrediction.c
Labels: Cleanup, P2
