Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-02, with the labels that each got.

#963 WIP Super-resolution tool - phase 1
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbCodingUnit.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.h
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbFullLoop.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.h
  Source/Lib/Encoder/Codec/EbResize.c
  Source/Lib/Encoder/Codec/EbResize.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbRestoration.c
  Source/Lib/Encoder/Codec/EbRestoration.h
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbSuperRes.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/api_test/params.h
Labels: P1

#987 Fix bitstream corruption: use init_sq_nsq_block instead of init_sq_non4_block
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#993 EbPictureManagerProcess: do not take an I_SLICE as global motion reference
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
Labels: P1, bugfix

#1003 Resolve library errors for binary identical test in Github Actions
  .github/workflows/svt-av1.yml
Labels: P1, bugfix, ci

#995 FFmpeg plugin: Update readme to use clone depth 1
  ffmpeg_plugin/README.md
Labels: documentation

#972 Packetization: fix Non-monotonous DTS
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Labels: ffmpeg

#1004 Ois memory reduction
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P1

#996 MD rate estimation enhancement
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, Q+

#997 ALT REF Filtering Improvement
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Labels: P1, Q+

#982 Fix valgrind issues
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#968 Support manual prediction structure
  Config/PredStruct_level0.cfg
  Config/PredStruct_level1.cfg
  Config/PredStruct_level2.cfg
  Config/PredStruct_level3.cfg
  Config/PredStruct_level4.cfg
  Config/PredStruct_level5.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/API/EbSvtAv1ErrorCodes.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncodeContext.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, new feature

#1002 Enhanced RDOQ
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbFullLoop.c
Labels: P1, Q+

#1009 4th MD Stage
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P1

#1006 Enhance SQ_WEIGHT
  Docs/Appendix-SQ-Weight.md
  Docs/README.md
  Docs/img/sq_weight_fig1.png
  Docs/img/sq_weight_fig2.png
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, S+

#1016 SequenceControlSet Copy
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
Labels: Cleanup, P1

#1019 Corrected Appendix Links
  Docs/svt-av1-encoder-design.md
Labels: documentation

#921 support hierarchical prediction structure level 5.
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, new feature

#1010 Tx Path Unification and Enhancements
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbFullLoop.h
  Source/Lib/Encoder/Codec/EbIntraPrediction.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: Cleanup, P1

#1011 nxm_sad_kernel_sub_sampled_helper_avx2 modification to call avx2 code for block width: 128, 48, 24
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
Labels: P1, simd

#1031 Revert unintentional change made by #963
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
Labels: P1, blocker, bugfix

#1015 Improve Warp motion
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbInterPrediction.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
Labels: P1, Q+

#967 distribute unit tests in GitHub CI
  .github/workflows/ci.yml
Labels: P1, test

#1028 Optimised Decoder LF flow, recon flow and CDEF intrinsic
  Source/App/DecApp/EbDecAppMain.c
  Source/Lib/Common/Codec/EbBlockStructures.h
  Source/Lib/Common/Codec/EbDeblockingCommon.c
  Source/Lib/Common/Codec/EbDeblockingCommon.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecLF.h
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseFrame.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbDecProcess.h
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.h
  Source/Lib/Decoder/Codec/EbDecProcessFrame.c
  Source/Lib/Encoder/ASM_AVX2/cdef_block_avx2.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
Labels: P1, decoder

#1027 Fix issues in manual prediction structure scheme
  Config/PredStruct_level5.cfg
  Source/Lib/Encoder/Codec/EbEncodeContext.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
Labels: P1, bugfix

#1038 Encoder common separation, PR 6
  Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
  Source/Lib/Common/ASM_SSE2/EbHighbdIntraPrediction_SSE2.h
  Source/Lib/Common/ASM_SSE2/EbIntraPrediction_AV1_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2.c
  Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2_.asm
  Source/Lib/Common/ASM_SSE2/intrapred_sse2.asm
  Source/Lib/Common/ASM_SSE2/lpf_common_sse2.h
  Source/Lib/Common/ASM_SSE2/subtract_sse2.asm
  Source/Lib/Common/ASM_SSE2/x86inc.asm
  Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/intrapred_ssse3.c
  Source/Lib/Common/Codec/EbBlockStructures.c
  Source/Lib/Common/Codec/EbBlockStructures.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbSuperRes.c
  Source/Lib/Common/Codec/EbSuperRes.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecStruct.h
  Source/Lib/Encoder/ASM_SSE2/CMakeLists.txt
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.h
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.h
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.h
  Source/Lib/Encoder/Codec/EbResize.c
  Source/Lib/Encoder/Codec/EbResize.h
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/AVCStyleMcpTest.cc
  test/EbSatdTest.cc
  test/PackUnPackTest.cc
  test/PictureAdditionTest.cc
  test/PictureOperatorTest.cc
  test/ResidualTest.cc
  test/TemporalFilterTest.cc
  test/subtract_avg_cfl_test.cc
Labels: Cleanup

#992 Fix all tests from SvtAv1E2ETests
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/api_test/SvtAv1EncParamsTest.cc
  test/e2e_test/SvtAv1E2EFramework.cc
  test/e2e_test/SvtAv1E2EParamsTest.cc
  test/e2e_test/SvtAv1E2ETest.cc
Labels: P1, test

#975 Travis CI: Add build jobs on other CPU architectures
  .travis.yml
Labels: build, ci

#1036 Add OVC Dockerfiles link
  README.md
Labels: documentation

#1037 cleanup: remove unused transform_inner_array_ptr in ModeDecisionContext and EncDecContext
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.h
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbTransforms.c
  Source/Lib/Encoder/Codec/EbTransforms.h
Labels: Cleanup

#1035 FullPel AVX512
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
Labels: P1, simd

#1041 add e2e tests in GitHub CI
  .github/workflows/ci.yml
Labels: P1, test

#1042 Add more test cases for deblocking test
  Source/Lib/Common/Codec/EbDeblockingCommon.c
  Source/Lib/Common/Codec/EbDeblockingCommon.h
  test/DeblockTest.cc
Labels: P1, test

#1025 Improve help menu:
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  gstreamer-plugin/gstsvtav1enc.c
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
  test/e2e_test/SvtAv1E2ETest.cc
Labels: P1, documentation

#1044 Fix mutex leak in debug mode and extra commented code
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
Labels: bugfix

#1045 Enc common separation 7
  Source/Lib/Common/Codec/EbBlockStructures.h
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecBlock.h
  Source/Lib/Decoder/Codec/EbDecCdef.c
  Source/Lib/Decoder/Codec/EbDecCdef.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecInverseQuantize.c
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.c
  Source/Lib/Decoder/Codec/EbDecParseHelper.h
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecProcessFrame.c
  Source/Lib/Decoder/Codec/EbObuParse.h
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Encoder/Codec/EbCodingUnit.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.h
Labels: Cleanup

#1050 Signal removal (code clean-up)
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup

#1040 Multi stages me
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, S+

#1005 Default -scm to 0
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1

#1059 Fix compilation error for old gcc
  Source/Lib/Common/ASM_AVX512/CMakeLists.txt
  Source/Lib/Common/ASM_AVX512/convolve_avx512.h
  Source/Lib/Common/ASM_AVX512/synonyms_avx512.h
  Source/Lib/Common/Codec/EbBlend_a64_mask.c
  Source/Lib/Encoder/ASM_AVX2/EbNoiseExtractAVX2.h
Labels: P1, blocker, build

#1057 Updated Multi-Pass-PD and MD-Staging Settings
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: Cleanup, P1, enhancement

#1051 16bit pipeline for filter
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbReferenceObject.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
Labels: P1, enhancement

#1056 enable ErrorFile for configuration file
  Config/Sample.cfg
  Source/App/EncApp/EbAppConfig.c
Labels: P1, bugfix

#1043 Rebase PME_SAD_OPT branch to make it applicable for master
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/C_DEFAULT/EbComputeSAD_C.c
  Source/Lib/Encoder/C_DEFAULT/EbComputeSAD_C.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/SadTest.cc
Labels: P1, simd

#1058 Prune Compound/Inter From Similar Blocks
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, enhancement

#1060 Tx Size Search for Depth_2
  Source/Lib/Common/Codec/EbCommonUtils.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.h
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbTransformUnit.h
Labels: P1, Q+, enhancement

#1063 Enhanced Nx4 & 4xN INTER candidates and 1/8 Pel ME MVs refinement
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, Q+

#1064 Travis CI: Fix dependencies not installing on macOS
  .travis.yml
Labels: ci

#1065 CI: Speed up AppVeyor by dropping VS debug job
  appveyor.yml
Labels: ci

#1055 Added more details to most kernels
  Docs/svt-av1_decoder_user_guide.md
  Docs/svt-av1_encoder_user_guide.md
  LICENSE_AOM.md
  README.md
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
Labels: documentation

#1067 distance based me
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Labels: P1, Q+

#1069 nic cleanup
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: Cleanup, P1

#1066 Added documentation on adaptive quantization
  Docs/Appendix-Variance-Based-Adaptive-Quantization.md
  Docs/README.md
  Docs/svt-av1-encoder-design.md
Labels: P1, documentation

#853 EbPictureBufferDesc: fix crash for none 16 aligned 10bits input
  Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/aom_subpixel_8t_intrin_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/highbd_jnt_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/jnt_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/txfm_common_avx2.h
  Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
  Source/Lib/Common/ASM_AVX512/convolve_2d_avx512.c
  Source/Lib/Common/ASM_AVX512/convolve_avx512.h
  Source/Lib/Common/ASM_AVX512/jnt_convolve_2d_avx512.c
  Source/Lib/Common/ASM_SSE2/EbDeblockingFilter_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbIntraPrediction_AV1_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/av1_txfm_sse2.h
  Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2.c
  Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2_.asm
  Source/Lib/Common/ASM_SSE2/subtract_sse2.asm
  Source/Lib/Common/ASM_SSE4_1/filterintra_sse4.c
  Source/Lib/Common/ASM_SSE4_1/highbd_inv_txfm_sse4.c
  Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/intrapred_ssse3.c
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/corner_match_avx2.c
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Encoder/ASM_AVX2/obmc_variance_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.h
  Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
  Source/Lib/Encoder/ASM_SSE2/encodetxb_sse2.c
  Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
  Source/Lib/Encoder/ASM_SSE4_1/highbd_fwd_txfm_sse4.c
Labels: P1, bugfix

#1071 Chroma search optimization 2
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, S+, enhancement

#1053 packetization_kernel: pack entire temproal unit for a output buffer
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Encoder/Codec/EbEncodeContext.h
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.c
  Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.h
  test/e2e_test/SvtAv1E2EFramework.cc
Labels: P1, bugfix

#1076 fix memory leaks for tile encoder
  Source/Lib/Encoder/Codec/EbEncDecSegments.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
Labels: bugfix

#1078 asm: change aligned read/store to unaligned read/store
  Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/aom_subpixel_8t_intrin_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/highbd_jnt_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/jnt_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/jnt_convolve_avx2.c
  Source/Lib/Common/ASM_AVX2/selfguided_avx2.c
  Source/Lib/Common/ASM_AVX2/synonyms_avx2.h
  Source/Lib/Common/ASM_AVX2/txfm_common_avx2.h
  Source/Lib/Common/ASM_AVX2/warp_plane_avx2.c
  Source/Lib/Common/ASM_AVX512/convolve_2d_avx512.c
  Source/Lib/Common/ASM_AVX512/convolve_avx512.c
  Source/Lib/Common/ASM_AVX512/jnt_convolve_2d_avx512.c
  Source/Lib/Common/ASM_AVX512/jnt_convolve_avx512.c
  Source/Lib/Encoder/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/fft_avx2.c
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_AVX512/highbd_fwd_txfm_AVX512.c
  Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
  Source/Lib/Encoder/ASM_SSE2/fft_sse2.c
Labels: bugfix, simd

#1084 Bug fixes in decoder related to segment id, delta lf, film grain, etc
  Source/App/DecApp/EbDecAppMain.c
  Source/Lib/Common/Codec/Av1Common.h
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/grainSynthesis.c
  Source/Lib/Decoder/Codec/EbDecBitstream.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.h
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbDecRestoration.c
Labels: P1, bugfix, decoder

#1097 Add tools on off cs2
  Docs/Appendix-CDEF.md
  Docs/Appendix-CfL.md
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: cs2
