Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-01, with the labels that each got.

#935 Rename get_mv to eb_get_mv to fix conflicts between libxvidcore
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
Labels: build

#938 Fix memory leak on EbModeDecisionProcess.c:L115
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
Labels: bugfix

#934 Added -vbv-bufsize to encoder doc.
  Docs/svt-av1_encoder_user_guide.md
Labels: documentation

#946 y4m error message fix
  Source/App/EncApp/EbAppInputy4m.c
Labels: bugfix

#948 fix rate control crash
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#942 windows: fix assert in GetFileType
  Source/App/EncApp/EbAppConfig.c
Labels: bugfix

#954 Fix Unit Tests
  Source/Lib/Encoder/ASM_AVX2/highbd_jnt_convolve_avx2.c
  Source/Lib/Encoder/ASM_AVX2/wiener_convolve_avx2.c
  test/SelfGuidedUtilTest.cc
  test/VarianceTest.cc
  test/wiener_convolve_test.cc
Labels: blocker, bugfix

#956 Minor clean up for resource allocation refactoring
  Source/Lib/Common/Codec/EbPictureBufferDesc.c
  Source/Lib/Encoder/Codec/EbCodingUnit.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncDecSegments.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.c
  Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionQueue.c
  Source/Lib/Encoder/Codec/EbPictureDecisionQueue.h
  Source/Lib/Encoder/Codec/EbPictureDecisionReorderQueue.c
  Source/Lib/Encoder/Codec/EbPictureDecisionReorderQueue.h
  Source/Lib/Encoder/Codec/EbPictureManagerQueue.c
  Source/Lib/Encoder/Codec/EbPictureManagerQueue.h
  Source/Lib/Encoder/Codec/EbPictureManagerReorderQueue.c
  Source/Lib/Encoder/Codec/EbPictureManagerReorderQueue.h
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbSystemResourceManager.c
  Source/Lib/Encoder/Codec/EbTransQuantBuffers.c
  Source/Lib/Encoder/Codec/noise_model.c
  test/FilmGrainTest.cc
  test/NoiseExtractTest.cc
Labels: Cleanup

#960 EbProductCodingLoop: fix valgrind errors
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: bugfix

#944 Fix mismatch between AVX512 and AVX2/C eb_av1_inv_txfm2d_add_64x16() kernel
  Source/Lib/Common/ASM_AVX512/highbd_inv_txfm_avx512.c
  test/InvTxfm2dAsmTest.cc
  test/TxfmCommon.h
Labels: blocker, bugfix, simd

#947 Add binary identical test for Github Actions
  .github/workflows/svt-av1.yml
Labels: ci

#970 Fix the tmvp issue
  Source/Lib/Encoder/Codec/EbCodingLoop.c
Labels: bugfix

#974 Fix the crash in debug mode
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: blocker, bugfix

#38 Add snapcraft.yaml
  snap/snapcraft.yaml
Labels: P1, build

#966 EbproductCodingLoop: fix valgrind errors
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: bugfix

#931 Actions/windows: Add MSVC job
  .github/workflows/msvc.yml
  Source/Lib/Common/ASM_SSE2/CMakeLists.txt
  Source/Lib/Encoder/ASM_SSE2/CMakeLists.txt
  Source/Lib/Encoder/ASM_SSSE3/CMakeLists.txt
Labels: ci

#895 interprediction remove av1_inter_prediction_hbd
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbInterPrediction.c
  Source/Lib/Encoder/Codec/EbInterPrediction.h
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Labels: Cleanup

#971 Enable tile parallelism
  Source/Lib/Common/Codec/EbBlockStructures.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureBufferDesc.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.h
  Source/Lib/Encoder/Codec/EbEncDecResults.h
  Source/Lib/Encoder/Codec/EbEncDecSegments.c
  Source/Lib/Encoder/Codec/EbEncDecTasks.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.h
  Source/Lib/Encoder/Codec/EbEntropyCodingObject.h
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.h
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, S+, blocker, bugfix, new feature

#969 fix sad unit test failure cases
  test/SadTest.cc
Labels: test

#976 Fix all tests from SvtAv1ApiTests
  Config/Sample.cfg
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/api_test/SvtAv1EncApiTest.cc
  test/api_test/params.h
Labels: test

#979 Revert "EbproductCodingLoop: fix valgrind errors (#966)"
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, blocker

#980 Update, Modify, Fix actions/travis
  .github/workflows/style-check.yml
  .github/workflows/svt-av1.yml
  .travis.yml
Labels: ci
