Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-05, with the labels that each got.

#1279 Travis: Re-enable travis-ci for pull requests
  .travis.yml
Labels: ci

#1273 Add protection for out of boundary
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#1278 Remove historic to do comments from libaom code
  Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInvTransforms.c
  Source/Lib/Common/Codec/EbRestoration.h
  Source/Lib/Common/Codec/EbWarpedMotion.c
  Source/Lib/Common/Codec/convolve.c
  Source/Lib/Common/Codec/convolve.h
  Source/Lib/Encoder/ASM_SSE2/variance_sse2.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPsnr.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbRestorationPick.c
  Source/Lib/Encoder/Codec/av1me.c
  Source/Lib/Encoder/Codec/corner_match.c
  Source/Lib/Encoder/Codec/global_motion.c
  Source/Lib/Encoder/Codec/hash_motion.c
Labels: Cleanup

#1274 Fix valgrind issue for: -w 640 -h 480 -enc-mode 8 -scm 1 -palette 3
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: Cleanup, P1, static/dynamic analysis

#1277 App: Add --no-progress option
  Docs/svt-av1_encoder_user_guide.md
  Source/App/DecApp/EbDecAppMain.c
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, enhancement

#1283 Fix wrong parameter for assert, 0 is valid
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
Labels: P1, bug

#1267 Update the Y sample buffer indexing for position A in Motion Estimation.
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
Labels: P1, bugfix

#1282 Travis-ci: Cleanup old jobs and yaml file
  .travis.yml
Labels: ci

#1265 Resolve the hang of 31B with lp=1 which is caused by lack of PA surfaces
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, bugfix

#1296 Remove the macro for 31B
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P1

#1288 EbAppMain, Ebthreads: use lowercase windows.h for case sensitive systems
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Common/Codec/EbThreads.h
Labels: build

#1294 Optimize performance reduce round() on double to int
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, enhancement

#1295 GCC10: Fix issues related to common symbols
  .github/workflows/ci.yml
  Source/Lib/Common/Codec/EbThreads.h
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, bugfix, build

#1286 Fix the R2R in M2 caused by uninitialized parameters
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#1298 Travis CI: Move to GCC 10
  .travis.yml
Labels: ci

#1299 ConfigureGitVersion: Remove --broken
  Source/Lib/Common/Codec/ConfigureGitVersion.cmake
Labels: bugfix, build

#1263 Fix inconsistent code
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbMcp.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPsnr.c
Labels: Cleanup, P1

#1292 CI: Error on warnings
  .github/workflows/ci.yml
Labels: ci

#1291 Enable svt_av1_apply_temporal_filter_planewise_avx2 kernel
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/TemporalFilterTestPlanewise.cc
Labels: P1, bugfix, simd

#1290 fix a bug of altref_strength calculation
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Labels: P1, bugfix

#1270 Add support for SSIM
  Source/API/EbSvtAv1.h
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbRestProcess.c
Labels: enhancement

#1249 CI: Add sanitizer runs
  .github/workflows/sanitizers.yml
  Source/Lib/Common/Codec/EbThreads.c
Labels: ci

#1300 Actions: Add releases job; Remove from appveyor
  .github/workflows/releases.yml
  CMakeLists.txt
  appveyor.yml
  third_party/googletest/CMakeLists.txt
Labels: ci

#1306 build.bat: Add static and shared options
  Build/windows/build.bat
Labels: build

#1310 Fix RC crash
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, bugfix

#1303 Add unit tests and e2e tests for MacOS CI
  .ci/ci.sh
  .github/workflows/macos.yml
Labels: ci, macos
