Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-10, with the labels that each got.

#1513 Align parameter defaults
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup

#1514 build.sh: Additional improvements
  Build/linux/build.sh
Labels: build

#1515 fix sub_sad/full_sad selection
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/firstpass.c
  test/SadTest.cc
Labels: Cleanup, bugfix

#1516 Port LibAom optimization and bug fixes
  Source/Lib/Common/ASM_AVX2/highbd_warp_affine_avx2.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.h
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/TemporalFilterTestPlanewise.cc
  test/warp_filter_test.cc
Labels: bugfix, simd

#1520 Fix nxm_sad_kernel_helper_avx2: Assertion `0' failed
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/C_DEFAULT/EbComputeSAD_C.c
  test/SadTest.cc
Labels: bugfix

#1519 Optimization of svt_av1_apply_temporal_filter_planewise
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
Labels: simd

#1530 Small speed improvement
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
  Source/Lib/Common/ASM_AVX512/highbd_inv_txfm_avx512.c
  Source/Lib/Common/ASM_SSE4_1/highbd_inv_txfm_sse4.c
  Source/Lib/Common/Codec/EbInvTransforms.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  test/InvTxfm2dAsmTest.cc
  test/InversetransformTests.cc
  test/ResidualTest.cc
Labels: S+, simd

#1524 refact, do not duplicate EbSvtAv1EncConfiguration's members in EbConfig
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppContext.h
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  test/e2e_test/ConfigEncoder.cc
  test/e2e_test/Y4mVideoSource.cc
Labels: Cleanup

#1551 Change --irefresh-type from 1 (open gop) to 2 (closed gop)
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: API Change, documentation
