Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-07, with the labels that each got.

#1336 Cppcheck-point 3
  Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
  Source/Lib/Common/ASM_AVX2/jnt_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/jnt_convolve_avx2.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbInvTransforms.c
  Source/Lib/Common/Codec/EbMalloc.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncDecSegments.c
Labels: static/dynamic analysis

#1360 Releases: pack releases using zip
  .github/workflows/releases.yml
Labels: ci

#1359 Fix for valgrind errors from Travis CI
  Source/Lib/Encoder/Codec/EbModeDecision.c
Labels: bugfix, static/dynamic analysis

#1364 cppcheck5: variableScope & unreadVariable
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbRestorationPick_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_highbd_sse4.c
  Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_sse4.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbNeighborArrays.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Labels: static/dynamic analysis

#1366 cppcheck6: variableScope etc
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Encoder/ASM_AVX2/EbCdef_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/obmc_variance_avx2.c
  Source/Lib/Encoder/ASM_AVX2/palette_avx2.c
  Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
  Source/Lib/Encoder/ASM_SSSE3/variance_impl_ssse3.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncDecSegments.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: static/dynamic analysis

#1368 cppcheck7: shadowVariable, knownConditionTrueFalse, & duplicateAssignExpression
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
  Source/Lib/Encoder/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/palette_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: static/dynamic analysis

#1353 Add protection when tile is enbaled and enc_dec segment number is reduced
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#1357 Use GST_ELEMENT_ERROR macro for GST_FLOW_ERROR
  gstreamer-plugin/gstsvtav1enc.c
Labels: gstreamer

#1370 Adoptions of fixes for R2R in 10bit from svt-01 branch
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: bugfix

#1371 Fix symbol conflicts with libaom and libopencore-amrwb
  Source/Lib/Common/ASM_AVX2/aom_subpixel_8t_intrin_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.c
  Source/Lib/Common/ASM_SSE4_1/EbBlend_a64_mask_sse4.c
  Source/Lib/Common/ASM_SSSE3/reconinter_ssse3.c
  Source/Lib/Common/Codec/EbCabacContextModel.c
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbSuperRes.c
  Source/Lib/Common/Codec/EbWarpedMotion.c
  Source/Lib/Common/Codec/EbWarpedMotion.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Common/Codec/convolve.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecSuperRes.c
  Source/Lib/Encoder/ASM_AVX2/highbd_variance_avx2.c
  Source/Lib/Encoder/ASM_SSE2/highbd_variance_impl_sse2.asm
  Source/Lib/Encoder/ASM_SSE2/highbd_variance_sse2.c
  Source/Lib/Encoder/ASM_SSE2/variance_sse2.c
  Source/Lib/Encoder/C_DEFAULT/variance.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.h
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEncWarpedMotion.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimationCost.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResize.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/av1me.c
  Source/Lib/Encoder/Codec/corner_match.c
  Source/Lib/Encoder/Codec/palette.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/CompoundUtilTest.cc
  test/EbBlend_a64_mask_1d_test.cc
  test/EbBlend_a64_mask_test.cc
  test/OBMCVarianceTest.cc
  test/PaletteModeUtilTest.cc
  test/WedgeUtilTest.cc
  test/intrapred_cfl_test.cc
Labels: blocker, build, ffmpeg

#1388 Fix valgrind for -tbr param
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
Labels: Rate Control

#1390 CMake: Move logic for asm_nasm debug format
  CMakeLists.txt
Labels: build

#1380 Fix enable-pic-based-rate-est and enable-intra-edge-skp params
  Source/App/EncApp/EbAppConfig.c
Labels: API Change

#1395 Travis CI: Allow failures on IBM Z job
  .travis.yml
Labels: ci

#1384 Fix read when -n > number of frames in y4m
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppInputy4m.h
  Source/App/EncApp/EbAppProcessCmd.c
Labels: bugfix

#1396 valgrind: Add an exit code if it is failing
  .travis.yml
Labels: ci
