Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-09, with the labels that each got.

#1456 Bug fixes related to QP assignment in 1 and 2 pass
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/pass2_strategy.c
Labels: bugfix

#1457 Pass1 speed up
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/firstpass.c
Labels: P1, S+, blocker

#1459 TPL fix
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#1455 Update documentation, Remove deprecated flags and update two pass information/flags
  Docs/svt-av1_encoder_user_guide.md
Labels: documentation

#1465 Fix TPL non16align error for openloop intra pred and dispenser
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
Labels: bugfix

#1462 Deadlock fix when keyint is not a multiple of lad
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#1461 Remove deprecated tokens , clean the app and update the encoder user guide
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: documentation

#1468 Kw fix
  Source/App/DecApp/EbDecAppMain.c
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/noise_model.c
  Source/Lib/Encoder/Codec/ransac.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/PaletteModeUtilTest.cc
  test/e2e_test/ConfigEncoder.cc
  test/warp_filter_test_util.cc
Labels: static/dynamic analysis

#1467 Implementation of kernel av1_haar_ac_sad_8x8_uint8_input_avx2
  Source/Lib/Encoder/ASM_AVX2/dwt_avx2.c
  Source/Lib/Encoder/Codec/EbTransforms.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/dwt.c
  Source/Lib/Encoder/Codec/dwt.h
  Source/Lib/Encoder/Codec/firstpass.c
  test/dwt_test.cc
Labels: simd

#1473 Cleanup all #if 0 and #if 1
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.h
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_SSE2/EbCombinedAveragingSAD_Intrinsic_SSE2.c
  Source/Lib/Encoder/ASM_SSE2/EbComputeSAD_SSE2.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/mcomp.c
  Source/Lib/Encoder/Codec/pass2_strategy.c
Labels: Cleanup

#1476 Run-time flags cleanup
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  gstreamer-plugin/gstsvtav1enc.c
Labels: Cleanup, documentation

#1479 2pass: fix crash for encode 100+ frames
  Source/Lib/Encoder/Codec/firstpass.c
Labels: bugfix

#1480 Legal notices updates
  CONTRIBUTING.md
  Docs/Notices.md
  Docs/svt-av1-encoder-design.md
  Docs/svt-av1_decoder_user_guide.md
  Docs/svt-av1_encoder_user_guide.md
  NOTICES.md
  PATENTS.md
  README.md
Labels: documentation

#1482 macos: Add execute bit before running unit tests
  .github/workflows/macos.yml
Labels: ci

#1481 Fix memory leaks from valgrind
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
Labels: bugfix

#1485 Fix mismatch C/AVX2 kernel svt_av1_apply_temporal_filter_planewise()
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Labels: simd

#1484 Bug fixes
  Source/API/EbDebugMacros.h
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/firstpass.c
Labels: bugfix

#1494 Add a the Contributing agreement links to be executed for contributions
  CONTRIBUTING.md
  README.md
  Source/API/EbDebugMacros.h
Labels: documentation

#1486 LtoWarnings: Fix some warnings that appear when trying to use lto
  Source/Lib/Encoder/Codec/EbCodingLoop.h
  Source/Lib/Encoder/Codec/EbEncInterPrediction.h
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  third_party/fastfeat/fast.c
Labels: build

#1493 avx2: eb_av1_haar_ac_sad_8x8_uint8_input_avx2, fix unaligned mov for transpose_32bit_8x8_avx2
  Source/Lib/Encoder/ASM_AVX2/dwt_avx2.c
Labels: bugfix

#1500 Fix r2r
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
Labels: bugfix

#1501 safestringlib: Compile strnlen_s based on availability
  CMakeLists.txt
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppMain.c
  third_party/safestringlib/CMakeLists.txt
Labels: Cleanup, documentation

#1506 Buildsh: Only use sudo if needed and some other cleanups
  Build/linux/build.sh
Labels: build

#1504 CMake: Add option to compile using C code only
  Build/linux/build.sh
  Build/windows/build.bat
  CMakeLists.txt
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/x86_abi_support.asm
  Source/Lib/Common/ASM_SSE2/x86inc.asm
  Source/Lib/Common/CMakeLists.txt
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/ASM_SSSE3/x86_abi_support.asm
  Source/Lib/Encoder/CMakeLists.txt
  Source/Lib/Encoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRestorationPick.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Codec/pass2_strategy.c
  Source/Lib/Encoder/Globals/CMakeLists.txt
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: build

#1508 Added explicit warning about rate control modes
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: documentation

#1495 Block 2-pass VBR when used with --rc 2 / 3
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, documentation

#1509 Time: Refactor time functions similar to SVT-VP9
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/App/EncApp/EbTime.c
  Source/App/EncApp/EbTime.h
  Source/Lib/Common/Codec/EbTime.c
  Source/Lib/Common/Codec/EbTime.h
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  test/CdefTest.cc
  test/EbUnitTestUtility.h
  test/EncodeTxbAsmTest.cc
  test/InvTxfm2dAsmTest.cc
  test/MotionEstimationTest.cc
  test/PaletteModeUtilTest.cc
  test/ResidualTest.cc
  test/RestorationPickTest.cc
  test/SadTest.cc
  test/SelfGuidedUtilTest.cc
  test/SpatialFullDistortionTest.cc
  test/TemporalFilterTestPlanewise.cc
  test/convolve_2d_test.cc
  test/corner_match_test.cc
  test/frame_error_test.cc
  test/quantize_func_test.cc
  test/selfguided_filter_test.cc
  test/warp_filter_test_util.cc
  test/wiener_convolve_test.cc
Labels: Cleanup
