Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-08, with the labels that each got.

#1383 actions: added libaom to ffmpeg to catch symbol conflicts and fix macOS symbol conflicts
  .github/workflows/mingw-w64.yml
  .github/workflows/patches.yml
  Source/Lib/Common/Codec/EbDeblockingCommon.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  test/DeblockTest.cc
Labels: ci

#1377 fix bug for two crash！
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#1399 macOS: Remove bazel
  .github/workflows/macos.yml
Labels: blocker, ci

#1392 Add pick_wedge_fixed_sign after estimating wedge_sign
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
Labels: bugfix

#1400 macOS: Set upgrade and install to force
  .github/workflows/macos.yml
Labels: ci

#1373 cppcheck: Memory related issues
  Source/App/EncApp/EbAppConfig.h
  Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMalloc.c
  Source/Lib/Common/Codec/EbMalloc.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  third_party/fastfeat/fast_9.c
Labels: static/dynamic analysis

#1401 clean and update ffmpeg plugin
  README.md
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  ffmpeg_plugin/README.md
Labels: ffmpeg

#1358 fix crash on Ctrl+C [WIP]
  Source/Lib/Common/Codec/EbThreads.c
Labels: WIP, bugfix

#1391 Sppeedup picture_sse_calculations by using SIMD kernels
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
Labels: simd

#1386 Quantization AVX2 intinsics code improvement: performance,code size &maintainability
  Source/Lib/Encoder/ASM_AVX2/highbd_quantize_intrin_avx2.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/QuantAsmTest.cc
Labels: simd

#1378 Generalize sad loop kernels
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  test/SadTest.cc
Labels: simd

#1416 Early tx_depth=2 exit
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbCodingLoop.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, S+

#1408 Svt-02 CLI features
  Config/Sample.cfg
  Docs/Appendix-Alt-Refs.md
  Docs/Appendix-CDEF.md
  Docs/Appendix-Palette-Prediction.md
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncCdef.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/palette.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  gstreamer-plugin/gstsvtav1enc.c
  test/api_test/SvtAv1EncParamsTest.cc
  test/api_test/params.h
  test/e2e_test/ParseUtil.cc
  test/e2e_test/RefDecoder.h
  test/e2e_test/SvtAv1E2ETest.cc
Labels: API Change

#1421 macOS: Delete build folder before reconfiguring cmake
  .github/workflows/macos.yml
Labels: build, macos

#1412 Increase references and WM candidates at MD stage 0 candidate generation
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, Q+, blocker

#1424 DecApp: Fix decoder segfault issues
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
Labels: bugfix

#1418 Fix AVX512, SAD_LOOP fix calculation 16,5 for search area 8,x or 16,x
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  test/SadTest.cc
Labels: simd

#1413 Improve INTER Pred
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbCodingUnit.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/av1me.c
  Source/Lib/Encoder/Codec/av1me.h
  Source/Lib/Encoder/Codec/mcomp.c
  Source/Lib/Encoder/Codec/mcomp.h
  Source/Lib/Encoder/Codec/mv.h
Labels: P1, Q+, S+, blocker

#1431 Two pass mode
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Common/Codec/Av1Common.h
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbBlockStructures.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncodeContext.c
  Source/Lib/Encoder/Codec/EbEncodeContext.h
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureDemuxResults.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/av1me.c
  Source/Lib/Encoder/Codec/av1me.h
  Source/Lib/Encoder/Codec/dwt.c
  Source/Lib/Encoder/Codec/dwt.h
  Source/Lib/Encoder/Codec/encoder.h
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Codec/firstpass.h
  Source/Lib/Encoder/Codec/level.c
  Source/Lib/Encoder/Codec/level.h
  Source/Lib/Encoder/Codec/mv.h
  Source/Lib/Encoder/Codec/noise_model.c
  Source/Lib/Encoder/Codec/pass2_strategy.c
  Source/Lib/Encoder/Codec/pass2_strategy.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Rate Control, blocker, enhancement

#1436 CMake: Use the compiler to actually detect if the 'cpu' is x86
  CMakeLists.txt
Labels: build

#1440 Decoder: Fix issues with the decoder not producing the correct output
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
Labels: P1, bugfix, decoder

#1439 Add a faster M7
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecision.h
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Codec/mcomp.c
Labels: P1, S+

#1361 App: Add option to print a bit more verbose or none as alternatives
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppMain.c
  Source/App/EncApp/EbAppProcessCmd.c
Labels: enhancement

#1432 Modification of sad_loop_kernel_{sse4_1/avx2/avx512} to support odd and even block width/height
  Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  test/SadTest.cc
Labels: simd

#1447 CMake: Add -fno-asynchronous-unwind-tables to flags if mingw
  CMakeLists.txt
Labels: build

#1448 Improve Lambda Generation and optimize preset trade-offs
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCodingLoop.h
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecision.h
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  gstreamer-plugin/gstsvtav1enc.c
Labels: P1, Q+, S+, blocker

#1445 Add support for gcc 4.8.5
  .github/workflows/ci.yml
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_SSE2/synonyms.h
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Encoder/Codec/palette.c
Labels: ci
