Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-04, with the labels that each got.

#1168 Fix windows debug build and fix typo
  Source/App/EncApp/EbAppConfig.c
Labels: build

#1180 Segfault fix
  Source/Lib/Encoder/Codec/EbRestProcess.c
Labels: P1, blocker, bugfix

#1154 valigrnd fix for mode_decision_update_neighbor_arrays
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#1163 Correctly use NULL for pointers in AomEquationSystem
  Source/Lib/Encoder/Codec/noise_model.c
Labels: P1, bugfix

#1169 EbPictureAnalysisProcess: assert sizes larger than 0
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
Labels: P1, static analysis

#1183 Fix UT, read outside of allocated memory
  test/PackUnPackTest.cc
Labels: P1, blocker, bugfix, test

#1186 fix INTRA_ANGLE_DELTA_NEW_TOKEN mapping
  Source/App/EncApp/EbAppConfig.c
Labels: bugfix

#1175 Add print CLI of SvtAv1EncApp when E2E test case failure
  test/e2e_test/ConfigEncoder.cc
  test/e2e_test/ConfigEncoder.h
  test/e2e_test/E2eTestVectors.h
  test/e2e_test/SvtAv1E2EFramework.cc
Labels: P1, test

#1187 Fix valgrind error for highbd_inv_txfm2d_add_h_identity_avx2
  Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
Labels: P1, bugfix

#1157 AVX2 kernel implementation
  Source/Lib/Common/ASM_AVX2/cfl_avx2.c
  Source/Lib/Common/Codec/EbCabacContextModel.c
  Source/Lib/Common/Codec/EbCabacContextModel.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/palette.c
  test/intrapred_cfl_test.cc
Labels: P1, simd

#1188 CI: Add simple cppcheck job
  .github/workflows/cppcheck.yml
Labels: P1, ci, test

#1204 Cleanup EbDefinitions.h
  Source/Lib/Common/Codec/EbDefinitions.h
Labels: Cleanup, P1

#951 [RFC] consistent namespacing for public API functions
  Source/API/EbSvtAv1Dec.h
  Source/API/EbSvtAv1Enc.h
  Source/App/DecApp/EbDecAppMain.c
  Source/App/EncApp/EbAppContext.c
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  gstreamer-plugin/gstsvtav1enc.c
  test/api_test/SvtAv1EncApiTest.cc
  test/api_test/SvtAv1EncParamsTest.cc
  test/e2e_test/ConfigEncoder.cc
  test/e2e_test/SvtAv1E2EFramework.cc
Labels: API Change, P1

#1210 Fix the r2r in entropy kernel
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
Labels: P1, blocker, bugfix

#1155 support c only build for non x86 platform
  .travis.yml
  Source/Lib/Common/ASM_SSE2/EbAvcStyleMcp_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
  Source/Lib/Common/CMakeLists.txt
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecRestoration.c
  Source/Lib/Encoder/CMakeLists.txt
  Source/Lib/Encoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbNeighborArrays.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbRestorationPick.c
  Source/Lib/Encoder/Codec/EbSegmentation.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Globals/CMakeLists.txt
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, blocker, simd

#1202 Remove EB_NULL
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbSystemResourceManager.c
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlReorderQueue.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
Labels: Cleanup

#1201 Fix bug in PackMsbTest
  test/PackUnPackTest.cc
Labels: P1, bugfix, test

#1189 Use dispatch semaphores on Darwin
  README.md
  Source/Lib/Common/Codec/EbThreads.c
Labels: P1, S+, blocker

#1191 fix encoding for non multiple-of-8 pictures
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbPictureBufferDesc.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, blocker, bugfix

#1207 Various fixes for cleaner code
  Source/Lib/Common/Codec/EbBitstreamUnit.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
Labels: P1, static analysis

#1217 Fix R2R caused by missing chroma data at boundary(#1079)
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
Labels: P1, bugfix

#1220 Print verbose version info in encoder and decoder
  CMakeLists.txt
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Common/Codec/ConfigureGitVersion.cmake
  Source/Lib/Common/Codec/EbVersion.h.in
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/Globals/CMakeLists.txt
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, enhancement

#1190 Fix pthread creation error handling
  Source/Lib/Common/Codec/EbThreads.c
Labels: Cleanup, P1

#1219 Decoder bug fix related to LR temp buffer and 16bit_pipeline
  Source/Lib/Common/Codec/EbRestoration.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecRestoration.c
Labels: P1, bugfix, decoder

#1224 Fix calling NULL pointer
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
Labels: P1, blocker, bugfix

#1232 Docs: Tell correct SCM default mode in EbAppConfig.C
  Source/App/EncApp/EbAppConfig.c
Labels: documentation

#1223 More style fixes
  Source/Lib/Common/ASM_SSE2/EbAvcStyleMcp_Intrinsic_SSE2.c
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
Labels: Cleanup, P1, static analysis

#1195 build.sh: fix an issue in arg splitting
  Build/linux/build.sh
Labels: Cleanup, P1

#1194 Update .clang-format
  .clang-format
Labels: P1, style

#415 CMake: Add code for Xcode generation
  .github/workflows/macos.yml
  CMakeLists.txt
  Source/Lib/Common/ASM_SSE2/CMakeLists.txt
  Source/Lib/Common/ASM_SSE2/x64inc.asm
  Source/Lib/Common/ASM_SSSE3/CMakeLists.txt
  Source/Lib/Common/CMakeLists.txt
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Encoder/ASM_SSE2/CMakeLists.txt
  Source/Lib/Encoder/ASM_SSSE3/CMakeLists.txt
  Source/Lib/Encoder/CMakeLists.txt
Labels: P2, build

#1149 Update presets for M0/M1 and further preset fixes
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/palette.c
Labels: P1, Q+

#1240 [GStreamer]Update SVT-AV1 interfaces
  .github/workflows/ci.yml
  gstreamer-plugin/CMakeLists.txt
  gstreamer-plugin/README.md
  gstreamer-plugin/gstsvtav1enc.c
  gstreamer-plugin/meson.build
Labels: blocker, gstreamer

#1244 ffmpeg: fix memory overwrite for complex video content
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: blocker, bugfix, ffmpeg

#1242 Add boundary check for predictive_me_search
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: bugfix

#1212 Support stdout for output
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
Labels: P1, enhancement

#1257 revert log2f changes due to rate loss
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbNeighborArrays.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSegmentation.c
Labels: P1, blocker, bugfix

#1259 Fix clang-cl build error
  Source/Lib/Encoder/Codec/k_means_template.h
Labels: build

#1243 Fixed CLI string in E2E tests
  test/e2e_test/E2eTestVectors.h
Labels: test

#1246 Fix: EbSvtAv1EncConfiguration.enable_manual_pred_struct is not set to EB_FALSE by default
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup

#1238 Fix for AVX2/AVX512 kernels when non-multiple of 8 resolution is used
  Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.c
  Source/Lib/Common/ASM_AVX512/wiener_convolve_avx512.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
  Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.h
  Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/RestorationPickTest.cc
  test/wiener_convolve_test.cc
Labels: P1, bugfix

#1264 CMake cleanups
  CMakeLists.txt
  Source/Lib/Common/CMakeLists.txt
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Encoder/CMakeLists.txt
  Source/Lib/Encoder/Codec/CMakeLists.txt
  Source/Lib/Encoder/Globals/CMakeLists.txt
Labels: Cleanup, build

#1255 Actions: Add macOS ffmpeg build and functionality test
  .github/workflows/ci.yml
Labels: ci

#1152 Super-resolution support for inter pictures
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbReferenceObject.c
  Source/Lib/Encoder/Codec/EbReferenceObject.h
  Source/Lib/Encoder/Codec/EbResize.c
  Source/Lib/Encoder/Codec/EbResize.h
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, enhancement

#1266 Fix log2f, and revert "Revert log2f changes due to rate loss
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.asm
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/EbUtility.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbNeighborArrays.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSegmentation.c
Labels: P1, bugfix

#1258 Fix R2R in non-8 aligned resolution streams
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Labels: P1, bugfix

#1211 Fix frames_to_be_encoded for non-file input
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
Labels: P1, enhancement

#1260 More cppcheck warning fixes
  Source/App/EncApp/EbTime.c
  Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX512/wiener_convolve_avx512.c
  Source/Lib/Common/ASM_SSE4_1/EbBlend_a64_mask_sse4.c
  Source/Lib/Common/Codec/EbBitstreamUnit.c
  Source/Lib/Common/Codec/EbCdef.c
  Source/Lib/Common/Codec/EbDeblockingCommon.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbIntraPrediction.c
  Source/Lib/Common/Codec/EbLog.c
  Source/Lib/Common/Codec/EbMalloc.c
  Source/Lib/Common/Codec/EbMalloc.h
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbTime.c
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Decoder/Codec/EbDecParseFrame.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Encoder/ASM_AVX2/obmc_sad_avx2.c
  Source/Lib/Encoder/ASM_AVX2/sse_avx2.c
  Source/Lib/Encoder/ASM_SSE2/variance_sse2.c
  Source/Lib/Encoder/C_DEFAULT/variance.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbEncWarpedMotion.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionReorderQueue.c
  Source/Lib/Encoder/Codec/EbPictureManagerReorderQueue.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResize.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/av1me.c
  Source/Lib/Encoder/Codec/corner_detect.c
  Source/Lib/Encoder/Codec/corner_match.c
  Source/Lib/Encoder/Codec/global_motion.c
  Source/Lib/Encoder/Codec/mathutils.h
  Source/Lib/Encoder/Codec/noise_util.c
  Source/Lib/Encoder/Codec/ransac.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P1
