Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-06, with the labels that each got.

#1317 Fix parameter name "AsmType" to "Asm" in Encoder User Guide.
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: documentation

#1316 Implementation of av1_apply_temporal_filter_planewise_hbd_avx2
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.h
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/TemporalFilterTestPlanewise.cc
Labels: P1, simd

#1313 EbAppConfig: Support double dashes for hme
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppMain.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup

#1275 Multi thread buffer tuning
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  gstreamer-plugin/gstsvtav1enc.c
Labels: P1, enhancement

#1320 Update PR template and the PR contributing guidelines
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation

#1323 CMake: Set W3 for MSVC
  CMakeLists.txt
Labels: build

#1304 CI: Clean up YAML files
  .ci/ci.sh
  .github/workflows/ci.yml
  .github/workflows/cppcheck.yml
  .github/workflows/macos.yml
  .github/workflows/msvc.yml
  .github/workflows/patches.yml
  .github/workflows/releases.yml
  .github/workflows/sanitizers.yml
  .github/workflows/style-check.yml
  .travis.yml
  appveyor.yml
  test/CMakeLists.txt
Labels: Cleanup, ci

#1177 size of n_alloc_len changes based on bitstream count
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, bugfix

#1326 ffmpeg: fix build for missing packet_internal.h
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: ffmpeg

#1324 CMake: Add error checking for nasm version, use ENABLE_NASM, don't check for nasm if non-x86
  .github/workflows/cppcheck.yml
  CMakeLists.txt
Labels: build

#1311 Implementation of variance_highbd_avx2 kernel
  Source/Lib/Encoder/ASM_AVX2/highbd_variance_avx2.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/HbdVarianceTest.cc
Labels: P1, enhancement, simd

#1335 Cppcheck-point 2
  Source/Lib/Common/ASM_AVX2/EbPackUnPack_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/cfl_avx2.c
  Source/Lib/Common/ASM_AVX2/convolve_avx2.h
  Source/Lib/Common/ASM_AVX2/highbd_convolve_2d_avx2.c
  Source/Lib/Common/ASM_AVX2/highbd_convolve_avx2.c
  Source/Lib/Common/ASM_SSE4_1/EbBlend_a64_mask_sse4.c
  Source/Lib/Common/ASM_SSE4_1/highbd_warp_plane_sse4.c
  Source/Lib/Common/C_DEFAULT/EbIntraPrediction_c.c
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/EbUtility.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
Labels: blocker, static/dynamic analysis

#1342 ffmpeg: Adapt with new libavcodec internal encode api changes
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Labels: ffmpeg

#1329 fixes symbols conflict with libaom.
  CMakeLists.txt
  Source/API/EbSvtAv1.h
  Source/Lib/Common/Codec/EbBitstreamUnit.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: ffmpeg

#1338 Cppcheck-point 4
  Source/Lib/Common/Codec/EbMalloc.h
  Source/Lib/Encoder/ASM_AVX2/EbCdef_AVX2.c
  Source/Lib/Encoder/ASM_AVX512/EbCdef_AVX512.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/CdefTest.cc
Labels: static/dynamic analysis

#1352 ffmpeg: correct rc mode and change forced-idr default to 1
  .github/workflows/style-check.yml
  Source/API/EbSvtAv1Enc.h
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
  ffmpeg_plugin/README.md
Labels: ffmpeg
