Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-12, with the labels that each got.

#1612 Fix issue with encoding using user defined prediction structure config
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
Labels: bugfix

#1615 Fix issue with hang-up on VBR encoding with specific conditions
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
Labels: bugfix

#1623 Gitlab CI additions
  .gitlab-ci.yml
Labels: ci

#1635 gitlab: add valgrind with pass 1 job
  .gitlab-ci.yml
Labels: ci

#1618 add support for specifying the per layer qindex offset
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbDebugMacros.h
  Source/API/EbSvtAv1.h
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: API Change

#1639 Only define export headers when building shared library.
  Source/API/EbSvtAv1.h
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Decoder/pkg-config.pc.in
  Source/Lib/Encoder/CMakeLists.txt
  Source/Lib/Encoder/Globals/CMakeLists.txt
  Source/Lib/Encoder/pkg-config.pc.in
Labels: Cleanup, build

#1647 gitlab: add FFmpeg linux build
  .gitlab-ci.yml
Labels: ci
