Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-11, with the labels that each got.

#1550 Fix some valgrind issues
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/firstpass.c
Labels: bug

#1559 Inloop TPL
  Source/API/EbDebugMacros.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbThreads.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncodeContext.h
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimationResults.h
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureDemuxResults.c
  Source/Lib/Encoder/Codec/EbPictureDemuxResults.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.h
  Source/Lib/Encoder/Codec/EbPictureManagerQueue.h
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.h
  Source/Lib/Encoder/Codec/EbRateControlTasks.h
  Source/Lib/Encoder/Codec/EbReferenceObject.c
  Source/Lib/Encoder/Codec/EbReferenceObject.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  Source/Lib/Encoder/Globals/EbEncHandle.h
  test/e2e_test/ConfigEncoder.cc
Labels: P1, Rate Control, enhancement

#1566 Fix valgrind v2
  Source/Lib/Encoder/Codec/firstpass.c
Labels: bugfix

#1560 remove restricting the maximum number of ME segments to 64
  Source/Lib/Common/Codec/Av1Common.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
Labels: bugfix

#1572 Faster preset
  Source/API/EbDebugMacros.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
  Source/Lib/Encoder/ASM_SSE2/encodetxb_sse2.c
  Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_highbd_sse4.c
  Source/Lib/Encoder/ASM_SSE4_1/highbd_fwd_txfm_sse4.c
  Source/Lib/Encoder/C_DEFAULT/EncodeTxbRef_C.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbCodingLoop.h
  Source/Lib/Encoder/Codec/EbCodingUnit.h
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncCdef.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbFullLoop.h
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecision.h
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationLcuResults.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.h
  Source/Lib/Encoder/Codec/EbReferenceObject.h
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.h
  Source/Lib/Encoder/Codec/EbTransforms.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/TemporalFilterTest.cc
Labels: P1, Q+, S+

#1571 Tune 0B/1B/3B settings to support minigop 1, 2 and 4
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbDebugMacros.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: enhancement

#1575 cleanup RPS
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.c
  Source/Lib/Encoder/Codec/EbPredictionStructure.h
Labels: Cleanup

#1576 add re-encode support for 2PASS and 2PASS VBR improvement
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbDebugMacros.h
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbCodingUnit.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncodeContext.c
  Source/Lib/Encoder/Codec/EbEncodeContext.h
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.h
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Codec/pass2_strategy.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Rate Control, enhancement

#1582 Cleanup macros to set kernel pointers
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
Labels: Cleanup

#1587 Preset tuning
  Source/API/EbDebugMacros.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/firstpass.c
Labels: P1, Q+, S+

#1602 Restructured First Pass
  Source/API/EbDebugMacros.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/firstpass.c
  Source/Lib/Encoder/Codec/firstpass.h
  Source/Lib/Encoder/Codec/pass2_strategy.c
  Source/Lib/Encoder/Codec/pass2_strategy.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, Rate Control

#1594 EbAppConfig: Rewrite find_token to fix assertion
  Source/App/EncApp/EbAppConfig.c
Labels: Cleanup

#1585 Sanitizer: Fix part of data race issues(#1308)
  .github/workflows/sanitizers-known-warnings.txt
  Source/App/EncApp/EbAppProcessCmd.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
Labels: bugfix

#1590 y4m: support y4m with header sizes up to 4096
  Source/App/EncApp/EbAppInputy4m.c
  Source/App/EncApp/EbAppInputy4m.h
  Source/App/EncApp/EbAppProcessCmd.c
Labels: bugfix, ffmpeg

#1606 CMake: add -mno-avx if -march=native is present
  CMakeLists.txt
Labels: build

#1609 Fix the 1 pass VBR tpl/lad setting
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#1600 Use cpuinfo to get cpu instruction set extension information
  CMakeLists.txt
  Source/Lib/Common/Codec/CMakeLists.txt
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Encoder/CMakeLists.txt
  test/CMakeLists.txt
  third_party/cpuinfo/CMakeLists.txt
  third_party/cpuinfo/LICENSE
  third_party/cpuinfo/deps/clog/CMakeLists.txt
  third_party/cpuinfo/deps/clog/LICENSE
  third_party/cpuinfo/deps/clog/include/clog.h
  third_party/cpuinfo/deps/clog/src/clog.c
  third_party/cpuinfo/include/cpuinfo.h
  third_party/cpuinfo/src/api.c
  third_party/cpuinfo/src/cpuinfo/common.h
  third_party/cpuinfo/src/cpuinfo/internal-api.h
  third_party/cpuinfo/src/cpuinfo/log.h
  third_party/cpuinfo/src/cpuinfo/utils.h
  third_party/cpuinfo/src/init.c
  third_party/cpuinfo/src/x86/api.h
  third_party/cpuinfo/src/x86/cpuid.h
  third_party/cpuinfo/src/x86/isa.c
  third_party/cpuinfo/src/x86/linux/init.c
  third_party/cpuinfo/src/x86/mach/x86_mach_init.c
  third_party/cpuinfo/src/x86/vendor.c
  third_party/cpuinfo/src/x86/windows/init.c
  third_party/cpuinfo/src/x86/x86_init.c
Labels: simd

#1610 v0.8.6 Prep
  CHANGELOG.md
  CMakeLists.txt
  Source/API/EbDebugMacros.h
  Source/API/EbSvtAv1.h
  Source/Lib/Decoder/CMakeLists.txt
  Source/Lib/Encoder/CMakeLists.txt
Labels: documentation
