Repository AOMediaCodec/SVT-AV1, pull requests merged in 2020-03, with the labels that each got.

#1090 10BIT bug fix
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, blocker, bugfix

#1080 Signal(s) clean-up
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/ASM_SSSE3/ml_ssse3.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationLcuResults.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  Source/Lib/Encoder/Codec/ml.c
  Source/Lib/Encoder/Codec/ml.h
  Source/Lib/Encoder/Codec/partition_model_weights.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
  test/EbNNPredictTests.cc
Labels: Cleanup, P1, blocker

#1073 build: fix debug build for gcc
  Source/Lib/Encoder/ASM_AVX2/EbNoiseExtractAVX2.c
Labels: build

#1068 More tools on off
  Docs/Appendix-CDEF.md
  Docs/Appendix-CfL.md
  Docs/Appendix-Intra-Block-Copy.md
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecParseBlock.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/av1me.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1

#1110 Adopt sb 128
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, Q+

#1089 refine unit test in github ci
  .github/workflows/ci.yml
Labels: P1, test

#1119 Fix lambda for HBD
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbEncCdef.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.h
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbTransforms.h
Labels: P1, Q+

#1113 Moved IFS from MD_STAGE_1 to MD_STAGE_3
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, S+

#1096 Modify NoiseExtractTest
  test/NoiseExtractTest.cc
Labels: test

#1108 Implementation of missing UT with bugfixes (import from cs2 branch)
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
  Source/Lib/Encoder/ASM_SSE2/variance_sse2.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/CompoundUtilTest.cc
  test/EbHighbdIntraPredictionTests.cc
  test/SadTest.cc
  test/WedgeUtilTest.cc
  test/intrapred_cfl_test.cc
Labels: test

#983 Actions: Add ffmpeg and gstreamer build
  .ci/ci.sh
  .github/workflows/ci.yml
Labels: ci

#1126 Bug fix in common inv_transform sse3 functions and decoder LF-MT
  Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
  Source/Lib/Decoder/Codec/EbDecLF.c
Labels: P1, bugfix, decoder

#1083 Bitstream: refact input params and hide implement details to make code more readable.
  Source/Lib/Common/Codec/EbBitstreamUnit.c
  Source/Lib/Common/Codec/EbBitstreamUnit.h
  Source/Lib/Encoder/Codec/EbEntropyCoding.c
  Source/Lib/Encoder/Codec/EbEntropyCoding.h
  Source/Lib/Encoder/Codec/EbEntropyCodingObject.h
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Labels: Cleanup, P1

#1112 Me nsq opt
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.h
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
Labels: P1, S+

#1092 packetization_kernel: fix missed last frame
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Labels: P1, blocker, bugfix

#1125 fixed run2run issue caused by uint32_t recon_offset
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_AVX512.h
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.h
  Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
  Source/Lib/Common/Codec/EbPictureOperators.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/SpatialFullDistortionTest.cc
Labels: P1, bugfix

#1117 Enhanced I_SICE QP assignment
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
Labels: P1, Q+

#1121 nsq_weight : skip NSQ partitions based on H vs V costs
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, S+

#1118 Shutdown threads in a graceful way
  Source/API/EbSvtAv1.h
  Source/Lib/Common/Codec/EbSystemResourceManager.c
  Source/Lib/Common/Codec/EbSystemResourceManager.h
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: bugfix

#1131 Address valgrind errors that could cause R2R issue and fix print message
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, bugfix

#1129 CI: Extend binary identical test to checkout target branch for pull request
  .github/workflows/ci.yml
Labels: ci, test

#1116 Fix crash during res release if res failed to allocate
  Source/Lib/Common/Codec/EbObject.h
  Source/Lib/Common/Codec/EbSystemResourceManager.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, bugfix

#1123 fixed gm_down bitstream corruption issue
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
Labels: P1, bugfix

#1128 Fix wiener convolve test crash
  test/wiener_convolve_test.cc
Labels: test

#1120 Enhanced tf
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.h
  Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/EbTemporalFiltering.h
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
Labels: P1, Q+

#1122 mrp and inter-intra clean ups
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
Labels: Cleanup, P1

#1132 Fix the r2r
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#1140 Structures cleanup
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P1

#1133 Memory Footprint Reduction
  Config/Sample.cfg
  Docs/svt-av1_encoder_user_guide.md
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/Codec/EbAv1Structs.h
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbCodingUnit.c
  Source/Lib/Encoder/Codec/EbCodingUnit.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEntropyCodingProcess.h
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbMdRateEstimation.h
  Source/Lib/Encoder/Codec/EbModeDecision.c
  Source/Lib/Encoder/Codec/EbModeDecision.h
  Source/Lib/Encoder/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.h
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbMotionEstimationLcuResults.h
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
  Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
  Source/Lib/Encoder/Codec/EbPredictionUnit.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbRateDistortionCost.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbTransformUnit.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: Cleanup, P1, memory

#1111 Skip depth optimisation
  Source/Lib/Encoder/Codec/EbCodingUnit.h
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, S+

#1143 Fix the r2r caused by wrong mv in warp case
  Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
Labels: P1, bugfix

#1144 Fix the r2r caused by the wrong neighbor array
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Labels: P1, bugfix

#1141 Improve CLI
  Docs/svt-av1_encoder_user_guide.md
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppMain.c
Labels: P1, documentation

#1147 Update command line parameters in the svt-av1_decoder_user_guide
  Docs/svt-av1_decoder_user_guide.md
Labels: documentation

#1150 code cleanup
  Source/Lib/Common/ASM_AVX2/EbPackUnPack_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPackUnPack_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_AVX512.h
  Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
  Source/Lib/Common/ASM_SSE2/EbMcp_SSE2.h
  Source/Lib/Common/ASM_SSE2/EbPackUnPack_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbPackUnPack_SSE2.h
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.asm
  Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.h
  Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_Intrinsic_SSSE3.c
  Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_SSSE3.h
  Source/Lib/Common/Codec/EbDeblockingCommon.c
  Source/Lib/Common/Codec/EbDeblockingCommon.h
  Source/Lib/Common/Codec/EbMcp.c
  Source/Lib/Common/Codec/EbPictureOperators.h
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Encoder/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.h
  Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/Encoder/ASM_AVX2/EbNoiseExtractAVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbNoiseExtractAVX2.h
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
  Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.h
  Source/Lib/Encoder/ASM_SSE2/EbComputeMean_SSE2.h
  Source/Lib/Encoder/ASM_SSE2/EbIntrinMacros16bit_SSE2.h
  Source/Lib/Encoder/ASM_SSE2/EbIntrinMacros_SSE2.h
  Source/Lib/Encoder/ASM_SSE2/EbMeSadCalculation_Intrinsic_SSE2.c
  Source/Lib/Encoder/ASM_SSE2/EbMeSadCalculation_SSE2.h
  Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
  Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_SSE4_1.h
  Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_sse4.c
  Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_sse4.h
  Source/Lib/Encoder/Codec/EbComputeMean.h
  Source/Lib/Encoder/Codec/EbComputeSAD.h
  Source/Lib/Encoder/Codec/EbDeblockingFilter.h
  Source/Lib/Encoder/Codec/EbMeSadCalculation.h
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.h
  Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.h
  Source/Lib/Encoder/Codec/EbTemporalFiltering.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/AVCStyleMcpTest.cc
  test/DeblockTest.cc
  test/MotionEstimationTest.cc
  test/NoiseExtractTest.cc
  test/PackUnPackTest.cc
  test/PictureOperatorTest.cc
  test/RestorationPickTest.cc
  test/SpatialFullDistortionTest.cc
  test/TemporalFilterTest.cc
  test/compute_mean_test.cc
  test/loopfilter_ref.h
Labels: Cleanup, P1, blocker

#1135 Update Sample.cfg
  Config/Sample.cfg
  Source/API/EbSvtAv1Enc.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: documentation

#1145 Fix r2r for -enable-overlays cases
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
  Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
Labels: P1, bugfix

#1148 Decoder design document
  Docs/README.md
  Docs/img/decoder_5_threads.png
  Docs/img/decoder_LF_horz.png
  Docs/img/decoder_LF_vert.png
  Docs/img/decoder_Nbr.png
  Docs/img/decoder_NbrOffset.png
  Docs/img/decoder_TileRowMT.png
  Docs/img/decoder_cdef_filter.png
  Docs/img/decoder_cdef_stage.png
  Docs/img/decoder_flow.png
  Docs/img/decoder_loop_filter_stage.png
  Docs/img/decoder_loop_restoration_stage.png
  Docs/img/decoder_main_thread.png
  Docs/img/decoder_parse_stage.png
  Docs/img/decoder_reconstruction_stage.png
  Docs/img/decoder_tile_parallel_l_gt_t.png
  Docs/img/decoder_tile_parallel_l_lt_t.png
  Docs/img/decoder_worker_thread.png
  Docs/svt-av1-decoder-design.md
Labels: documentation

#1151 EbPacketizationProcess: do not push alt ref frame to undisplayed queue
  Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Labels: P1, bugfix

#1162 EbFileUtils: fix handling of a 0 frame unit size
  Source/App/DecApp/EbFileUtils.c
Labels: P1, bugfix

#1138 16bit pipeline support
  Source/API/EbSvtAv1Dec.h
  Source/API/EbSvtAv1Enc.h
  Source/App/DecApp/EbDecParamParser.c
  Source/App/DecApp/EbDecParamParser.h
  Source/App/EncApp/EbAppConfig.c
  Source/App/EncApp/EbAppConfig.h
  Source/App/EncApp/EbAppContext.c
  Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
  Source/Lib/Common/C_DEFAULT/EbPackUnPack_C.c
  Source/Lib/Common/C_DEFAULT/EbPackUnPack_C.h
  Source/Lib/Common/Codec/EbDefinitions.h
  Source/Lib/Common/Codec/EbInterPrediction.c
  Source/Lib/Common/Codec/EbInterPrediction.h
  Source/Lib/Common/Codec/EbInvTransforms.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.c
  Source/Lib/Common/Codec/EbPictureBufferDesc.h
  Source/Lib/Common/Codec/EbRestoration.c
  Source/Lib/Common/Codec/EbSuperRes.c
  Source/Lib/Common/Codec/common_dsp_rtcd.c
  Source/Lib/Common/Codec/common_dsp_rtcd.h
  Source/Lib/Decoder/Codec/EbDecCdef.c
  Source/Lib/Decoder/Codec/EbDecHandle.c
  Source/Lib/Decoder/Codec/EbDecHandle.h
  Source/Lib/Decoder/Codec/EbDecInterPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
  Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
  Source/Lib/Decoder/Codec/EbDecLF.c
  Source/Lib/Decoder/Codec/EbDecMemInit.c
  Source/Lib/Decoder/Codec/EbDecMemInit.h
  Source/Lib/Decoder/Codec/EbDecObmc.c
  Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
  Source/Lib/Decoder/Codec/EbDecParseObu.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.c
  Source/Lib/Decoder/Codec/EbDecPicMgr.h
  Source/Lib/Decoder/Codec/EbDecProcess.c
  Source/Lib/Decoder/Codec/EbDecProcessBlock.c
  Source/Lib/Decoder/Codec/EbDecRestoration.c
  Source/Lib/Decoder/Codec/EbDecSuperRes.c
  Source/Lib/Decoder/Codec/EbDecUtils.c
  Source/Lib/Encoder/Codec/EbCdefProcess.c
  Source/Lib/Encoder/Codec/EbCodingLoop.c
  Source/Lib/Encoder/Codec/EbDeblockingFilter.c
  Source/Lib/Encoder/Codec/EbDlfProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.c
  Source/Lib/Encoder/Codec/EbEncDecProcess.h
  Source/Lib/Encoder/Codec/EbEncInterPrediction.c
  Source/Lib/Encoder/Codec/EbEncInterPrediction.h
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.c
  Source/Lib/Encoder/Codec/EbEncIntraPrediction.h
  Source/Lib/Encoder/Codec/EbFullLoop.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbProductCodingLoop.c
  Source/Lib/Encoder/Codec/EbReferenceObject.c
  Source/Lib/Encoder/Codec/EbRestProcess.c
  Source/Lib/Encoder/Codec/EbSequenceControlSet.c
  Source/Lib/Encoder/Codec/EbTransforms.c
  Source/Lib/Encoder/Codec/EbTransforms.h
  Source/Lib/Encoder/Globals/EbEncHandle.c
Labels: P1, blocker, new feature

#1153 Add GitHub CI configuration for Windows
  .github/workflows/msvc.yml
Labels: P1, test

#1166 EbMotionEstimation: add assert in default case
  Source/Lib/Encoder/Codec/EbMotionEstimation.c
Labels: P1, bugfix
