Repository AOMediaCodec/SVT-AV1, pull requests merged in 2021-01, with the labels that each got.

#1651 Fix some deadlock issues
  Source/API/EbDebugMacros.h
  Source/Lib/Common/Codec/EbThreads.c
  Source/Lib/Common/Codec/EbThreads.h
  Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
  Source/Lib/Encoder/Codec/EbPictureControlSet.h
  Source/Lib/Encoder/Codec/EbRateControlProcess.c
  Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Labels: bugfix

#1662 cppcheck: suppress unused functions and extra messages
  .github/workflows/cppcheck.yml
  .gitlab-ci.yml
Labels: ci

#1660 Fix kernel svt_aom_highbd_10_variance16x4_avx2,
  Source/Lib/Encoder/ASM_AVX2/highbd_variance_avx2.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
  Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
  test/HbdVarianceTest.cc
Labels: simd

#1665 gitlab: add windows ffmpeg build
  .gitlab-ci.yml
Labels: ci

#1579 Travis CI: Update to Ubuntu 20.04 and remove IBM Z allow_failure
  .travis.yml
Labels: ci

#1680 Gitlab: Cleanup and add missmatch test
  .gitlab-ci.yml
Labels: ci
